// Package v1beta2 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version v2.0.0-20260512191121-23c2b5646dfc+dirty DO NOT EDIT.
package v1beta2

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for BucketInventoryAPIVersion.
const (
	BucketInventoryAPIVersions3AwsUpboundIoV1Beta2 BucketInventoryAPIVersion = "s3.aws.upbound.io/v1beta2"
)

// Valid indicates whether the value is a known member of the BucketInventoryAPIVersion enum.
func (e BucketInventoryAPIVersion) Valid() bool {
	switch e {
	case BucketInventoryAPIVersions3AwsUpboundIoV1Beta2:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventoryKind.
const (
	BucketInventoryKindBucketInventory BucketInventoryKind = "BucketInventory"
)

// Valid indicates whether the value is a known member of the BucketInventoryKind enum.
func (e BucketInventoryKind) Valid() bool {
	switch e {
	case BucketInventoryKindBucketInventory:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecDeletionPolicy.
const (
	BucketInventorySpecDeletionPolicyDelete BucketInventorySpecDeletionPolicy = "Delete"
	BucketInventorySpecDeletionPolicyOrphan BucketInventorySpecDeletionPolicy = "Orphan"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecDeletionPolicy enum.
func (e BucketInventorySpecDeletionPolicy) Valid() bool {
	switch e {
	case BucketInventorySpecDeletionPolicyDelete:
		return true
	case BucketInventorySpecDeletionPolicyOrphan:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecForProviderBucketRefPolicyResolution.
const (
	BucketInventorySpecForProviderBucketRefPolicyResolutionOptional BucketInventorySpecForProviderBucketRefPolicyResolution = "Optional"
	BucketInventorySpecForProviderBucketRefPolicyResolutionRequired BucketInventorySpecForProviderBucketRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecForProviderBucketRefPolicyResolution enum.
func (e BucketInventorySpecForProviderBucketRefPolicyResolution) Valid() bool {
	switch e {
	case BucketInventorySpecForProviderBucketRefPolicyResolutionOptional:
		return true
	case BucketInventorySpecForProviderBucketRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecForProviderBucketRefPolicyResolve.
const (
	BucketInventorySpecForProviderBucketRefPolicyResolveAlways       BucketInventorySpecForProviderBucketRefPolicyResolve = "Always"
	BucketInventorySpecForProviderBucketRefPolicyResolveIfNotPresent BucketInventorySpecForProviderBucketRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecForProviderBucketRefPolicyResolve enum.
func (e BucketInventorySpecForProviderBucketRefPolicyResolve) Valid() bool {
	switch e {
	case BucketInventorySpecForProviderBucketRefPolicyResolveAlways:
		return true
	case BucketInventorySpecForProviderBucketRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecForProviderBucketSelectorPolicyResolution.
const (
	BucketInventorySpecForProviderBucketSelectorPolicyResolutionOptional BucketInventorySpecForProviderBucketSelectorPolicyResolution = "Optional"
	BucketInventorySpecForProviderBucketSelectorPolicyResolutionRequired BucketInventorySpecForProviderBucketSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecForProviderBucketSelectorPolicyResolution enum.
func (e BucketInventorySpecForProviderBucketSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketInventorySpecForProviderBucketSelectorPolicyResolutionOptional:
		return true
	case BucketInventorySpecForProviderBucketSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecForProviderBucketSelectorPolicyResolve.
const (
	BucketInventorySpecForProviderBucketSelectorPolicyResolveAlways       BucketInventorySpecForProviderBucketSelectorPolicyResolve = "Always"
	BucketInventorySpecForProviderBucketSelectorPolicyResolveIfNotPresent BucketInventorySpecForProviderBucketSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecForProviderBucketSelectorPolicyResolve enum.
func (e BucketInventorySpecForProviderBucketSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketInventorySpecForProviderBucketSelectorPolicyResolveAlways:
		return true
	case BucketInventorySpecForProviderBucketSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolution.
const (
	BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolutionOptional BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolution = "Optional"
	BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolutionRequired BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolution enum.
func (e BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolution) Valid() bool {
	switch e {
	case BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolutionOptional:
		return true
	case BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolve.
const (
	BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolveAlways       BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolve = "Always"
	BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolveIfNotPresent BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolve enum.
func (e BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolve) Valid() bool {
	switch e {
	case BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolveAlways:
		return true
	case BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolution.
const (
	BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolutionOptional BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolution = "Optional"
	BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolutionRequired BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolution enum.
func (e BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolutionOptional:
		return true
	case BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolve.
const (
	BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolveAlways       BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolve = "Always"
	BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolveIfNotPresent BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolve enum.
func (e BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolveAlways:
		return true
	case BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecInitProviderBucketRefPolicyResolution.
const (
	BucketInventorySpecInitProviderBucketRefPolicyResolutionOptional BucketInventorySpecInitProviderBucketRefPolicyResolution = "Optional"
	BucketInventorySpecInitProviderBucketRefPolicyResolutionRequired BucketInventorySpecInitProviderBucketRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecInitProviderBucketRefPolicyResolution enum.
func (e BucketInventorySpecInitProviderBucketRefPolicyResolution) Valid() bool {
	switch e {
	case BucketInventorySpecInitProviderBucketRefPolicyResolutionOptional:
		return true
	case BucketInventorySpecInitProviderBucketRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecInitProviderBucketRefPolicyResolve.
const (
	BucketInventorySpecInitProviderBucketRefPolicyResolveAlways       BucketInventorySpecInitProviderBucketRefPolicyResolve = "Always"
	BucketInventorySpecInitProviderBucketRefPolicyResolveIfNotPresent BucketInventorySpecInitProviderBucketRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecInitProviderBucketRefPolicyResolve enum.
func (e BucketInventorySpecInitProviderBucketRefPolicyResolve) Valid() bool {
	switch e {
	case BucketInventorySpecInitProviderBucketRefPolicyResolveAlways:
		return true
	case BucketInventorySpecInitProviderBucketRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecInitProviderBucketSelectorPolicyResolution.
const (
	BucketInventorySpecInitProviderBucketSelectorPolicyResolutionOptional BucketInventorySpecInitProviderBucketSelectorPolicyResolution = "Optional"
	BucketInventorySpecInitProviderBucketSelectorPolicyResolutionRequired BucketInventorySpecInitProviderBucketSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecInitProviderBucketSelectorPolicyResolution enum.
func (e BucketInventorySpecInitProviderBucketSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketInventorySpecInitProviderBucketSelectorPolicyResolutionOptional:
		return true
	case BucketInventorySpecInitProviderBucketSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecInitProviderBucketSelectorPolicyResolve.
const (
	BucketInventorySpecInitProviderBucketSelectorPolicyResolveAlways       BucketInventorySpecInitProviderBucketSelectorPolicyResolve = "Always"
	BucketInventorySpecInitProviderBucketSelectorPolicyResolveIfNotPresent BucketInventorySpecInitProviderBucketSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecInitProviderBucketSelectorPolicyResolve enum.
func (e BucketInventorySpecInitProviderBucketSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketInventorySpecInitProviderBucketSelectorPolicyResolveAlways:
		return true
	case BucketInventorySpecInitProviderBucketSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolution.
const (
	BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolutionOptional BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolution = "Optional"
	BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolutionRequired BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolution enum.
func (e BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolution) Valid() bool {
	switch e {
	case BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolutionOptional:
		return true
	case BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolve.
const (
	BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolveAlways       BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolve = "Always"
	BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolveIfNotPresent BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolve enum.
func (e BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolve) Valid() bool {
	switch e {
	case BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolveAlways:
		return true
	case BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolution.
const (
	BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolutionOptional BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolution = "Optional"
	BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolutionRequired BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolution enum.
func (e BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolutionOptional:
		return true
	case BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolve.
const (
	BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolveAlways       BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolve = "Always"
	BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolveIfNotPresent BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolve enum.
func (e BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolveAlways:
		return true
	case BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecManagementPoliciesItem.
const (
	BucketInventorySpecManagementPoliciesItemBucketInventorySpecManagementPoliciesItem               BucketInventorySpecManagementPoliciesItem = "*"
	BucketInventorySpecManagementPoliciesItemBucketInventorySpecManagementPoliciesItemCreate         BucketInventorySpecManagementPoliciesItem = "Create"
	BucketInventorySpecManagementPoliciesItemBucketInventorySpecManagementPoliciesItemDelete         BucketInventorySpecManagementPoliciesItem = "Delete"
	BucketInventorySpecManagementPoliciesItemBucketInventorySpecManagementPoliciesItemLateInitialize BucketInventorySpecManagementPoliciesItem = "LateInitialize"
	BucketInventorySpecManagementPoliciesItemBucketInventorySpecManagementPoliciesItemObserve        BucketInventorySpecManagementPoliciesItem = "Observe"
	BucketInventorySpecManagementPoliciesItemBucketInventorySpecManagementPoliciesItemUpdate         BucketInventorySpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecManagementPoliciesItem enum.
func (e BucketInventorySpecManagementPoliciesItem) Valid() bool {
	switch e {
	case BucketInventorySpecManagementPoliciesItemBucketInventorySpecManagementPoliciesItem:
		return true
	case BucketInventorySpecManagementPoliciesItemBucketInventorySpecManagementPoliciesItemCreate:
		return true
	case BucketInventorySpecManagementPoliciesItemBucketInventorySpecManagementPoliciesItemDelete:
		return true
	case BucketInventorySpecManagementPoliciesItemBucketInventorySpecManagementPoliciesItemLateInitialize:
		return true
	case BucketInventorySpecManagementPoliciesItemBucketInventorySpecManagementPoliciesItemObserve:
		return true
	case BucketInventorySpecManagementPoliciesItemBucketInventorySpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecProviderConfigRefPolicyResolution.
const (
	BucketInventorySpecProviderConfigRefPolicyResolutionOptional BucketInventorySpecProviderConfigRefPolicyResolution = "Optional"
	BucketInventorySpecProviderConfigRefPolicyResolutionRequired BucketInventorySpecProviderConfigRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecProviderConfigRefPolicyResolution enum.
func (e BucketInventorySpecProviderConfigRefPolicyResolution) Valid() bool {
	switch e {
	case BucketInventorySpecProviderConfigRefPolicyResolutionOptional:
		return true
	case BucketInventorySpecProviderConfigRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketInventorySpecProviderConfigRefPolicyResolve.
const (
	BucketInventorySpecProviderConfigRefPolicyResolveAlways       BucketInventorySpecProviderConfigRefPolicyResolve = "Always"
	BucketInventorySpecProviderConfigRefPolicyResolveIfNotPresent BucketInventorySpecProviderConfigRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketInventorySpecProviderConfigRefPolicyResolve enum.
func (e BucketInventorySpecProviderConfigRefPolicyResolve) Valid() bool {
	switch e {
	case BucketInventorySpecProviderConfigRefPolicyResolveAlways:
		return true
	case BucketInventorySpecProviderConfigRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// IoUpboundAwsS3V1Beta2BucketInventory BucketInventory is the Schema for the BucketInventorys API. Provides a S3 bucket inventory configuration resource.
type IoUpboundAwsS3V1Beta2BucketInventory = BucketInventory

// BucketInventoryAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type BucketInventoryAPIVersion string

// BucketInventoryKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type BucketInventoryKind string

// BucketInventorySpecDeletionPolicy DeletionPolicy specifies what will happen to the underlying external
// when this managed resource is deleted - either "Delete" or "Orphan" the
// external resource.
// This field is planned to be deprecated in favor of the ManagementPolicies
// field in a future release. Currently, both could be set independently and
// non-default values would be honored if the feature flag is enabled.
// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
type BucketInventorySpecDeletionPolicy string

// BucketInventorySpecForProviderBucketRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketInventorySpecForProviderBucketRefPolicyResolution string

// BucketInventorySpecForProviderBucketRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketInventorySpecForProviderBucketRefPolicyResolve string

// BucketInventorySpecForProviderBucketRefPolicy Policies for referencing.
type BucketInventorySpecForProviderBucketRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketInventorySpecForProviderBucketRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketInventorySpecForProviderBucketRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketInventorySpecForProviderBucketRef Reference to a Bucket in s3 to populate bucket.
type BucketInventorySpecForProviderBucketRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketInventorySpecForProviderBucketRefPolicy `json:"policy,omitempty"`
}

// BucketInventorySpecForProviderBucketSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketInventorySpecForProviderBucketSelectorPolicyResolution string

// BucketInventorySpecForProviderBucketSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketInventorySpecForProviderBucketSelectorPolicyResolve string

// BucketInventorySpecForProviderBucketSelectorPolicy Policies for selection.
type BucketInventorySpecForProviderBucketSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketInventorySpecForProviderBucketSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketInventorySpecForProviderBucketSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketInventorySpecForProviderBucketSelector Selector for a Bucket in s3 to populate bucket.
type BucketInventorySpecForProviderBucketSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *BucketInventorySpecForProviderBucketSelectorPolicy `json:"policy,omitempty"`
}

// BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolution string

// BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolve string

// BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicy Policies for referencing.
type BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketInventorySpecForProviderDestinationBucketBucketArnRef Reference to a Bucket in s3 to populate bucketArn.
type BucketInventorySpecForProviderDestinationBucketBucketArnRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketInventorySpecForProviderDestinationBucketBucketArnRefPolicy `json:"policy,omitempty"`
}

// BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolution string

// BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolve string

// BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicy Policies for selection.
type BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketInventorySpecForProviderDestinationBucketBucketArnSelector Selector for a Bucket in s3 to populate bucketArn.
type BucketInventorySpecForProviderDestinationBucketBucketArnSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *BucketInventorySpecForProviderDestinationBucketBucketArnSelectorPolicy `json:"policy,omitempty"`
}

// BucketInventorySpecForProviderDestinationBucketEncryptionSseKms Specifies to use server-side encryption with AWS KMS-managed keys to encrypt the inventory file (documented below).
type BucketInventorySpecForProviderDestinationBucketEncryptionSseKms struct {
	// KeyID ARN of the KMS customer master key (CMK) used to encrypt the inventory file.
	KeyID *string `json:"keyId,omitempty"`
}

// BucketInventorySpecForProviderDestinationBucketEncryptionSseS3 Specifies to use server-side encryption with Amazon S3-managed keys (SSE-S3) to encrypt the inventory file.
type BucketInventorySpecForProviderDestinationBucketEncryptionSseS3 = map[string]interface{}

// BucketInventorySpecForProviderDestinationBucketEncryption Contains the type of server-side encryption to use to encrypt the inventory (documented below).
type BucketInventorySpecForProviderDestinationBucketEncryption struct {
	// SseKms Specifies to use server-side encryption with AWS KMS-managed keys to encrypt the inventory file (documented below).
	SseKms *BucketInventorySpecForProviderDestinationBucketEncryptionSseKms `json:"sseKms,omitempty"`

	// SseS3 Specifies to use server-side encryption with Amazon S3-managed keys (SSE-S3) to encrypt the inventory file.
	SseS3 *BucketInventorySpecForProviderDestinationBucketEncryptionSseS3 `json:"sseS3,omitempty"`
}

// BucketInventorySpecForProviderDestinationBucket Name of the source bucket that inventory lists the objects for.
type BucketInventorySpecForProviderDestinationBucket struct {
	// AccountID ID of the account that owns the destination bucket. Recommended to be set to prevent problems if the destination bucket ownership changes.
	AccountID *string `json:"accountId,omitempty"`

	// BucketArn Amazon S3 bucket ARN of the destination.
	BucketArn *string `json:"bucketArn,omitempty"`

	// BucketArnRef Reference to a Bucket in s3 to populate bucketArn.
	BucketArnRef *BucketInventorySpecForProviderDestinationBucketBucketArnRef `json:"bucketArnRef,omitempty"`

	// BucketArnSelector Selector for a Bucket in s3 to populate bucketArn.
	BucketArnSelector *BucketInventorySpecForProviderDestinationBucketBucketArnSelector `json:"bucketArnSelector,omitempty"`

	// Encryption Contains the type of server-side encryption to use to encrypt the inventory (documented below).
	Encryption *BucketInventorySpecForProviderDestinationBucketEncryption `json:"encryption,omitempty"`

	// Format Specifies the output format of the inventory results. Can be CSV, ORC or Parquet.
	Format *string `json:"format,omitempty"`

	// Prefix Prefix that an object must have to be included in the inventory results.
	Prefix *string `json:"prefix,omitempty"`
}

// BucketInventorySpecForProviderDestination Contains information about where to publish the inventory results (documented below).
type BucketInventorySpecForProviderDestination struct {
	// Bucket Name of the source bucket that inventory lists the objects for.
	Bucket *BucketInventorySpecForProviderDestinationBucket `json:"bucket,omitempty"`
}

// BucketInventorySpecForProviderFilter Specifies an inventory filter. The inventory only includes objects that meet the filter's criteria (documented below).
type BucketInventorySpecForProviderFilter struct {
	// Prefix Prefix that an object must have to be included in the inventory results.
	Prefix *string `json:"prefix,omitempty"`
}

// BucketInventorySpecForProviderSchedule Specifies the schedule for generating inventory results (documented below).
type BucketInventorySpecForProviderSchedule struct {
	// Frequency Specifies how frequently inventory results are produced. Valid values: Daily, Weekly.
	Frequency *string `json:"frequency,omitempty"`
}

// BucketInventorySpecForProvider defines model for .
type BucketInventorySpecForProvider struct {
	// Bucket Name of the source bucket that inventory lists the objects for.
	Bucket *string `json:"bucket,omitempty"`

	// BucketRef Reference to a Bucket in s3 to populate bucket.
	BucketRef *BucketInventorySpecForProviderBucketRef `json:"bucketRef,omitempty"`

	// BucketSelector Selector for a Bucket in s3 to populate bucket.
	BucketSelector *BucketInventorySpecForProviderBucketSelector `json:"bucketSelector,omitempty"`

	// Destination Contains information about where to publish the inventory results (documented below).
	Destination *BucketInventorySpecForProviderDestination `json:"destination,omitempty"`

	// Enabled Specifies whether the inventory is enabled or disabled.
	Enabled *bool `json:"enabled,omitempty"`

	// Filter Specifies an inventory filter. The inventory only includes objects that meet the filter's criteria (documented below).
	Filter *BucketInventorySpecForProviderFilter `json:"filter,omitempty"`

	// IncludedObjectVersions Object versions to include in the inventory list. Valid values: All, Current.
	IncludedObjectVersions *string `json:"includedObjectVersions,omitempty"`

	// Name Unique identifier of the inventory configuration for the bucket.
	Name *string `json:"name,omitempty"`

	// OptionalFields List of optional fields that are included in the inventory results. Please refer to the S3 documentation for more details.
	OptionalFields *[]string `json:"optionalFields,omitempty"`

	// Region Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty"`

	// Schedule Specifies the schedule for generating inventory results (documented below).
	Schedule *BucketInventorySpecForProviderSchedule `json:"schedule,omitempty"`
}

// BucketInventorySpecInitProviderBucketRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketInventorySpecInitProviderBucketRefPolicyResolution string

// BucketInventorySpecInitProviderBucketRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketInventorySpecInitProviderBucketRefPolicyResolve string

// BucketInventorySpecInitProviderBucketRefPolicy Policies for referencing.
type BucketInventorySpecInitProviderBucketRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketInventorySpecInitProviderBucketRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketInventorySpecInitProviderBucketRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketInventorySpecInitProviderBucketRef Reference to a Bucket in s3 to populate bucket.
type BucketInventorySpecInitProviderBucketRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketInventorySpecInitProviderBucketRefPolicy `json:"policy,omitempty"`
}

// BucketInventorySpecInitProviderBucketSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketInventorySpecInitProviderBucketSelectorPolicyResolution string

// BucketInventorySpecInitProviderBucketSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketInventorySpecInitProviderBucketSelectorPolicyResolve string

// BucketInventorySpecInitProviderBucketSelectorPolicy Policies for selection.
type BucketInventorySpecInitProviderBucketSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketInventorySpecInitProviderBucketSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketInventorySpecInitProviderBucketSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketInventorySpecInitProviderBucketSelector Selector for a Bucket in s3 to populate bucket.
type BucketInventorySpecInitProviderBucketSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *BucketInventorySpecInitProviderBucketSelectorPolicy `json:"policy,omitempty"`
}

// BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolution string

// BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolve string

// BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicy Policies for referencing.
type BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketInventorySpecInitProviderDestinationBucketBucketArnRef Reference to a Bucket in s3 to populate bucketArn.
type BucketInventorySpecInitProviderDestinationBucketBucketArnRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketInventorySpecInitProviderDestinationBucketBucketArnRefPolicy `json:"policy,omitempty"`
}

// BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolution string

// BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolve string

// BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicy Policies for selection.
type BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketInventorySpecInitProviderDestinationBucketBucketArnSelector Selector for a Bucket in s3 to populate bucketArn.
type BucketInventorySpecInitProviderDestinationBucketBucketArnSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *BucketInventorySpecInitProviderDestinationBucketBucketArnSelectorPolicy `json:"policy,omitempty"`
}

// BucketInventorySpecInitProviderDestinationBucketEncryptionSseKms Specifies to use server-side encryption with AWS KMS-managed keys to encrypt the inventory file (documented below).
type BucketInventorySpecInitProviderDestinationBucketEncryptionSseKms struct {
	// KeyID ARN of the KMS customer master key (CMK) used to encrypt the inventory file.
	KeyID *string `json:"keyId,omitempty"`
}

// BucketInventorySpecInitProviderDestinationBucketEncryptionSseS3 Specifies to use server-side encryption with Amazon S3-managed keys (SSE-S3) to encrypt the inventory file.
type BucketInventorySpecInitProviderDestinationBucketEncryptionSseS3 = map[string]interface{}

// BucketInventorySpecInitProviderDestinationBucketEncryption Contains the type of server-side encryption to use to encrypt the inventory (documented below).
type BucketInventorySpecInitProviderDestinationBucketEncryption struct {
	// SseKms Specifies to use server-side encryption with AWS KMS-managed keys to encrypt the inventory file (documented below).
	SseKms *BucketInventorySpecInitProviderDestinationBucketEncryptionSseKms `json:"sseKms,omitempty"`

	// SseS3 Specifies to use server-side encryption with Amazon S3-managed keys (SSE-S3) to encrypt the inventory file.
	SseS3 *BucketInventorySpecInitProviderDestinationBucketEncryptionSseS3 `json:"sseS3,omitempty"`
}

// BucketInventorySpecInitProviderDestinationBucket Name of the source bucket that inventory lists the objects for.
type BucketInventorySpecInitProviderDestinationBucket struct {
	// AccountID ID of the account that owns the destination bucket. Recommended to be set to prevent problems if the destination bucket ownership changes.
	AccountID *string `json:"accountId,omitempty"`

	// BucketArn Amazon S3 bucket ARN of the destination.
	BucketArn *string `json:"bucketArn,omitempty"`

	// BucketArnRef Reference to a Bucket in s3 to populate bucketArn.
	BucketArnRef *BucketInventorySpecInitProviderDestinationBucketBucketArnRef `json:"bucketArnRef,omitempty"`

	// BucketArnSelector Selector for a Bucket in s3 to populate bucketArn.
	BucketArnSelector *BucketInventorySpecInitProviderDestinationBucketBucketArnSelector `json:"bucketArnSelector,omitempty"`

	// Encryption Contains the type of server-side encryption to use to encrypt the inventory (documented below).
	Encryption *BucketInventorySpecInitProviderDestinationBucketEncryption `json:"encryption,omitempty"`

	// Format Specifies the output format of the inventory results. Can be CSV, ORC or Parquet.
	Format *string `json:"format,omitempty"`

	// Prefix Prefix that an object must have to be included in the inventory results.
	Prefix *string `json:"prefix,omitempty"`
}

// BucketInventorySpecInitProviderDestination Contains information about where to publish the inventory results (documented below).
type BucketInventorySpecInitProviderDestination struct {
	// Bucket Name of the source bucket that inventory lists the objects for.
	Bucket *BucketInventorySpecInitProviderDestinationBucket `json:"bucket,omitempty"`
}

// BucketInventorySpecInitProviderFilter Specifies an inventory filter. The inventory only includes objects that meet the filter's criteria (documented below).
type BucketInventorySpecInitProviderFilter struct {
	// Prefix Prefix that an object must have to be included in the inventory results.
	Prefix *string `json:"prefix,omitempty"`
}

// BucketInventorySpecInitProviderSchedule Specifies the schedule for generating inventory results (documented below).
type BucketInventorySpecInitProviderSchedule struct {
	// Frequency Specifies how frequently inventory results are produced. Valid values: Daily, Weekly.
	Frequency *string `json:"frequency,omitempty"`
}

// BucketInventorySpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type BucketInventorySpecInitProvider struct {
	// Bucket Name of the source bucket that inventory lists the objects for.
	Bucket *string `json:"bucket,omitempty"`

	// BucketRef Reference to a Bucket in s3 to populate bucket.
	BucketRef *BucketInventorySpecInitProviderBucketRef `json:"bucketRef,omitempty"`

	// BucketSelector Selector for a Bucket in s3 to populate bucket.
	BucketSelector *BucketInventorySpecInitProviderBucketSelector `json:"bucketSelector,omitempty"`

	// Destination Contains information about where to publish the inventory results (documented below).
	Destination *BucketInventorySpecInitProviderDestination `json:"destination,omitempty"`

	// Enabled Specifies whether the inventory is enabled or disabled.
	Enabled *bool `json:"enabled,omitempty"`

	// Filter Specifies an inventory filter. The inventory only includes objects that meet the filter's criteria (documented below).
	Filter *BucketInventorySpecInitProviderFilter `json:"filter,omitempty"`

	// IncludedObjectVersions Object versions to include in the inventory list. Valid values: All, Current.
	IncludedObjectVersions *string `json:"includedObjectVersions,omitempty"`

	// Name Unique identifier of the inventory configuration for the bucket.
	Name *string `json:"name,omitempty"`

	// OptionalFields List of optional fields that are included in the inventory results. Please refer to the S3 documentation for more details.
	OptionalFields *[]string `json:"optionalFields,omitempty"`

	// Schedule Specifies the schedule for generating inventory results (documented below).
	Schedule *BucketInventorySpecInitProviderSchedule `json:"schedule,omitempty"`
}

// BucketInventorySpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type BucketInventorySpecManagementPoliciesItem string

// BucketInventorySpecProviderConfigRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketInventorySpecProviderConfigRefPolicyResolution string

// BucketInventorySpecProviderConfigRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketInventorySpecProviderConfigRefPolicyResolve string

// BucketInventorySpecProviderConfigRefPolicy Policies for referencing.
type BucketInventorySpecProviderConfigRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketInventorySpecProviderConfigRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketInventorySpecProviderConfigRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketInventorySpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type BucketInventorySpecProviderConfigRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketInventorySpecProviderConfigRefPolicy `json:"policy,omitempty"`
}

// BucketInventorySpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type BucketInventorySpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// BucketInventorySpec BucketInventorySpec defines the desired state of BucketInventory
type BucketInventorySpec struct {
	// DeletionPolicy DeletionPolicy specifies what will happen to the underlying external
	// when this managed resource is deleted - either "Delete" or "Orphan" the
	// external resource.
	// This field is planned to be deprecated in favor of the ManagementPolicies
	// field in a future release. Currently, both could be set independently and
	// non-default values would be honored if the feature flag is enabled.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	DeletionPolicy *BucketInventorySpecDeletionPolicy `json:"deletionPolicy,omitempty"`
	ForProvider    *BucketInventorySpecForProvider    `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *BucketInventorySpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// This field is planned to replace the DeletionPolicy field in a future
	// release. Currently, both could be set independently and non-default
	// values would be honored if the feature flag is enabled. If both are
	// custom, the DeletionPolicy field will be ignored.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]BucketInventorySpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *BucketInventorySpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *BucketInventorySpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// BucketInventoryStatusAtProviderDestinationBucketEncryptionSseKms Specifies to use server-side encryption with AWS KMS-managed keys to encrypt the inventory file (documented below).
type BucketInventoryStatusAtProviderDestinationBucketEncryptionSseKms struct {
	// KeyID ARN of the KMS customer master key (CMK) used to encrypt the inventory file.
	KeyID *string `json:"keyId,omitempty"`
}

// BucketInventoryStatusAtProviderDestinationBucketEncryptionSseS3 Specifies to use server-side encryption with Amazon S3-managed keys (SSE-S3) to encrypt the inventory file.
type BucketInventoryStatusAtProviderDestinationBucketEncryptionSseS3 = map[string]interface{}

// BucketInventoryStatusAtProviderDestinationBucketEncryption Contains the type of server-side encryption to use to encrypt the inventory (documented below).
type BucketInventoryStatusAtProviderDestinationBucketEncryption struct {
	// SseKms Specifies to use server-side encryption with AWS KMS-managed keys to encrypt the inventory file (documented below).
	SseKms *BucketInventoryStatusAtProviderDestinationBucketEncryptionSseKms `json:"sseKms,omitempty"`

	// SseS3 Specifies to use server-side encryption with Amazon S3-managed keys (SSE-S3) to encrypt the inventory file.
	SseS3 *BucketInventoryStatusAtProviderDestinationBucketEncryptionSseS3 `json:"sseS3,omitempty"`
}

// BucketInventoryStatusAtProviderDestinationBucket Name of the source bucket that inventory lists the objects for.
type BucketInventoryStatusAtProviderDestinationBucket struct {
	// AccountID ID of the account that owns the destination bucket. Recommended to be set to prevent problems if the destination bucket ownership changes.
	AccountID *string `json:"accountId,omitempty"`

	// BucketArn Amazon S3 bucket ARN of the destination.
	BucketArn *string `json:"bucketArn,omitempty"`

	// Encryption Contains the type of server-side encryption to use to encrypt the inventory (documented below).
	Encryption *BucketInventoryStatusAtProviderDestinationBucketEncryption `json:"encryption,omitempty"`

	// Format Specifies the output format of the inventory results. Can be CSV, ORC or Parquet.
	Format *string `json:"format,omitempty"`

	// Prefix Prefix that an object must have to be included in the inventory results.
	Prefix *string `json:"prefix,omitempty"`
}

// BucketInventoryStatusAtProviderDestination Contains information about where to publish the inventory results (documented below).
type BucketInventoryStatusAtProviderDestination struct {
	// Bucket Name of the source bucket that inventory lists the objects for.
	Bucket *BucketInventoryStatusAtProviderDestinationBucket `json:"bucket,omitempty"`
}

// BucketInventoryStatusAtProviderFilter Specifies an inventory filter. The inventory only includes objects that meet the filter's criteria (documented below).
type BucketInventoryStatusAtProviderFilter struct {
	// Prefix Prefix that an object must have to be included in the inventory results.
	Prefix *string `json:"prefix,omitempty"`
}

// BucketInventoryStatusAtProviderSchedule Specifies the schedule for generating inventory results (documented below).
type BucketInventoryStatusAtProviderSchedule struct {
	// Frequency Specifies how frequently inventory results are produced. Valid values: Daily, Weekly.
	Frequency *string `json:"frequency,omitempty"`
}

// BucketInventoryStatusAtProvider defines model for .
type BucketInventoryStatusAtProvider struct {
	// Bucket Name of the source bucket that inventory lists the objects for.
	Bucket *string `json:"bucket,omitempty"`

	// Destination Contains information about where to publish the inventory results (documented below).
	Destination *BucketInventoryStatusAtProviderDestination `json:"destination,omitempty"`

	// Enabled Specifies whether the inventory is enabled or disabled.
	Enabled *bool `json:"enabled,omitempty"`

	// Filter Specifies an inventory filter. The inventory only includes objects that meet the filter's criteria (documented below).
	Filter *BucketInventoryStatusAtProviderFilter `json:"filter,omitempty"`
	ID     *string                                `json:"id,omitempty"`

	// IncludedObjectVersions Object versions to include in the inventory list. Valid values: All, Current.
	IncludedObjectVersions *string `json:"includedObjectVersions,omitempty"`

	// Name Unique identifier of the inventory configuration for the bucket.
	Name *string `json:"name,omitempty"`

	// OptionalFields List of optional fields that are included in the inventory results. Please refer to the S3 documentation for more details.
	OptionalFields *[]string `json:"optionalFields,omitempty"`

	// Region Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty"`

	// Schedule Specifies the schedule for generating inventory results (documented below).
	Schedule *BucketInventoryStatusAtProviderSchedule `json:"schedule,omitempty"`
}

// BucketInventoryStatusConditionsItem A Condition that may apply to a resource.
type BucketInventoryStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// BucketInventoryStatus BucketInventoryStatus defines the observed state of BucketInventory.
type BucketInventoryStatus struct {
	AtProvider *BucketInventoryStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]BucketInventoryStatusConditionsItem `json:"conditions,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// BucketInventory BucketInventory is the Schema for the BucketInventorys API. Provides a S3 bucket inventory configuration resource.
type BucketInventory struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *BucketInventoryAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *BucketInventoryKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec BucketInventorySpec defines the desired state of BucketInventory
	Spec *BucketInventorySpec `json:"spec,omitempty"`

	// Status BucketInventoryStatus defines the observed state of BucketInventory.
	Status *BucketInventoryStatus `json:"status,omitempty"`
}

// IoUpboundAwsS3V1Beta2BucketInventoryList BucketInventoryList is a list of BucketInventory
type IoUpboundAwsS3V1Beta2BucketInventoryList = BucketInventoryList

// BucketInventoryList BucketInventoryList is a list of BucketInventory
type BucketInventoryList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of bucketinventories. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundAwsS3V1Beta2BucketInventory `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
