apiVersion: dev.crossplane.io/v1alpha1
kind: Project
metadata:
  name: example-project-webapp
spec:
  dependencies:
  - type: xpkg
    xpkg:
      apiVersion: pkg.crossplane.io/v1
      kind: Function
      package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready
      version: '>=v0.0.0'
  - k8s:
      version: v1.35.0
    type: k8s
  repository: example.com/my-org/example-project-webapp
