// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version v2.0.0-20260512191121-23c2b5646dfc+dirty DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for BucketMetricAPIVersion.
const (
	BucketMetricAPIVersions3AwsUpboundIoV1Beta1 BucketMetricAPIVersion = "s3.aws.upbound.io/v1beta1"
)

// Valid indicates whether the value is a known member of the BucketMetricAPIVersion enum.
func (e BucketMetricAPIVersion) Valid() bool {
	switch e {
	case BucketMetricAPIVersions3AwsUpboundIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricKind.
const (
	BucketMetricKindBucketMetric BucketMetricKind = "BucketMetric"
)

// Valid indicates whether the value is a known member of the BucketMetricKind enum.
func (e BucketMetricKind) Valid() bool {
	switch e {
	case BucketMetricKindBucketMetric:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecDeletionPolicy.
const (
	BucketMetricSpecDeletionPolicyDelete BucketMetricSpecDeletionPolicy = "Delete"
	BucketMetricSpecDeletionPolicyOrphan BucketMetricSpecDeletionPolicy = "Orphan"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecDeletionPolicy enum.
func (e BucketMetricSpecDeletionPolicy) Valid() bool {
	switch e {
	case BucketMetricSpecDeletionPolicyDelete:
		return true
	case BucketMetricSpecDeletionPolicyOrphan:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecForProviderBucketRefPolicyResolution.
const (
	BucketMetricSpecForProviderBucketRefPolicyResolutionOptional BucketMetricSpecForProviderBucketRefPolicyResolution = "Optional"
	BucketMetricSpecForProviderBucketRefPolicyResolutionRequired BucketMetricSpecForProviderBucketRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecForProviderBucketRefPolicyResolution enum.
func (e BucketMetricSpecForProviderBucketRefPolicyResolution) Valid() bool {
	switch e {
	case BucketMetricSpecForProviderBucketRefPolicyResolutionOptional:
		return true
	case BucketMetricSpecForProviderBucketRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecForProviderBucketRefPolicyResolve.
const (
	BucketMetricSpecForProviderBucketRefPolicyResolveAlways       BucketMetricSpecForProviderBucketRefPolicyResolve = "Always"
	BucketMetricSpecForProviderBucketRefPolicyResolveIfNotPresent BucketMetricSpecForProviderBucketRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecForProviderBucketRefPolicyResolve enum.
func (e BucketMetricSpecForProviderBucketRefPolicyResolve) Valid() bool {
	switch e {
	case BucketMetricSpecForProviderBucketRefPolicyResolveAlways:
		return true
	case BucketMetricSpecForProviderBucketRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecForProviderBucketSelectorPolicyResolution.
const (
	BucketMetricSpecForProviderBucketSelectorPolicyResolutionOptional BucketMetricSpecForProviderBucketSelectorPolicyResolution = "Optional"
	BucketMetricSpecForProviderBucketSelectorPolicyResolutionRequired BucketMetricSpecForProviderBucketSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecForProviderBucketSelectorPolicyResolution enum.
func (e BucketMetricSpecForProviderBucketSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketMetricSpecForProviderBucketSelectorPolicyResolutionOptional:
		return true
	case BucketMetricSpecForProviderBucketSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecForProviderBucketSelectorPolicyResolve.
const (
	BucketMetricSpecForProviderBucketSelectorPolicyResolveAlways       BucketMetricSpecForProviderBucketSelectorPolicyResolve = "Always"
	BucketMetricSpecForProviderBucketSelectorPolicyResolveIfNotPresent BucketMetricSpecForProviderBucketSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecForProviderBucketSelectorPolicyResolve enum.
func (e BucketMetricSpecForProviderBucketSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketMetricSpecForProviderBucketSelectorPolicyResolveAlways:
		return true
	case BucketMetricSpecForProviderBucketSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolution.
const (
	BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolutionOptional BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolution = "Optional"
	BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolutionRequired BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolution enum.
func (e BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolution) Valid() bool {
	switch e {
	case BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolutionOptional:
		return true
	case BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolve.
const (
	BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolveAlways       BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolve = "Always"
	BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolveIfNotPresent BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolve enum.
func (e BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolve) Valid() bool {
	switch e {
	case BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolveAlways:
		return true
	case BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolution.
const (
	BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolutionOptional BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolution = "Optional"
	BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolutionRequired BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolution enum.
func (e BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolutionOptional:
		return true
	case BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolve.
const (
	BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolveAlways       BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolve = "Always"
	BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolveIfNotPresent BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolve enum.
func (e BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolveAlways:
		return true
	case BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecInitProviderBucketRefPolicyResolution.
const (
	BucketMetricSpecInitProviderBucketRefPolicyResolutionOptional BucketMetricSpecInitProviderBucketRefPolicyResolution = "Optional"
	BucketMetricSpecInitProviderBucketRefPolicyResolutionRequired BucketMetricSpecInitProviderBucketRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecInitProviderBucketRefPolicyResolution enum.
func (e BucketMetricSpecInitProviderBucketRefPolicyResolution) Valid() bool {
	switch e {
	case BucketMetricSpecInitProviderBucketRefPolicyResolutionOptional:
		return true
	case BucketMetricSpecInitProviderBucketRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecInitProviderBucketRefPolicyResolve.
const (
	BucketMetricSpecInitProviderBucketRefPolicyResolveAlways       BucketMetricSpecInitProviderBucketRefPolicyResolve = "Always"
	BucketMetricSpecInitProviderBucketRefPolicyResolveIfNotPresent BucketMetricSpecInitProviderBucketRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecInitProviderBucketRefPolicyResolve enum.
func (e BucketMetricSpecInitProviderBucketRefPolicyResolve) Valid() bool {
	switch e {
	case BucketMetricSpecInitProviderBucketRefPolicyResolveAlways:
		return true
	case BucketMetricSpecInitProviderBucketRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecInitProviderBucketSelectorPolicyResolution.
const (
	BucketMetricSpecInitProviderBucketSelectorPolicyResolutionOptional BucketMetricSpecInitProviderBucketSelectorPolicyResolution = "Optional"
	BucketMetricSpecInitProviderBucketSelectorPolicyResolutionRequired BucketMetricSpecInitProviderBucketSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecInitProviderBucketSelectorPolicyResolution enum.
func (e BucketMetricSpecInitProviderBucketSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketMetricSpecInitProviderBucketSelectorPolicyResolutionOptional:
		return true
	case BucketMetricSpecInitProviderBucketSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecInitProviderBucketSelectorPolicyResolve.
const (
	BucketMetricSpecInitProviderBucketSelectorPolicyResolveAlways       BucketMetricSpecInitProviderBucketSelectorPolicyResolve = "Always"
	BucketMetricSpecInitProviderBucketSelectorPolicyResolveIfNotPresent BucketMetricSpecInitProviderBucketSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecInitProviderBucketSelectorPolicyResolve enum.
func (e BucketMetricSpecInitProviderBucketSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketMetricSpecInitProviderBucketSelectorPolicyResolveAlways:
		return true
	case BucketMetricSpecInitProviderBucketSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolution.
const (
	BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolutionOptional BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolution = "Optional"
	BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolutionRequired BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolution enum.
func (e BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolution) Valid() bool {
	switch e {
	case BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolutionOptional:
		return true
	case BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolve.
const (
	BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolveAlways       BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolve = "Always"
	BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolveIfNotPresent BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolve enum.
func (e BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolve) Valid() bool {
	switch e {
	case BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolveAlways:
		return true
	case BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolution.
const (
	BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolutionOptional BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolution = "Optional"
	BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolutionRequired BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolution enum.
func (e BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolutionOptional:
		return true
	case BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolve.
const (
	BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolveAlways       BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolve = "Always"
	BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolveIfNotPresent BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolve enum.
func (e BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolveAlways:
		return true
	case BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecManagementPoliciesItem.
const (
	BucketMetricSpecManagementPoliciesItemBucketMetricSpecManagementPoliciesItem               BucketMetricSpecManagementPoliciesItem = "*"
	BucketMetricSpecManagementPoliciesItemBucketMetricSpecManagementPoliciesItemCreate         BucketMetricSpecManagementPoliciesItem = "Create"
	BucketMetricSpecManagementPoliciesItemBucketMetricSpecManagementPoliciesItemDelete         BucketMetricSpecManagementPoliciesItem = "Delete"
	BucketMetricSpecManagementPoliciesItemBucketMetricSpecManagementPoliciesItemLateInitialize BucketMetricSpecManagementPoliciesItem = "LateInitialize"
	BucketMetricSpecManagementPoliciesItemBucketMetricSpecManagementPoliciesItemObserve        BucketMetricSpecManagementPoliciesItem = "Observe"
	BucketMetricSpecManagementPoliciesItemBucketMetricSpecManagementPoliciesItemUpdate         BucketMetricSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecManagementPoliciesItem enum.
func (e BucketMetricSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case BucketMetricSpecManagementPoliciesItemBucketMetricSpecManagementPoliciesItem:
		return true
	case BucketMetricSpecManagementPoliciesItemBucketMetricSpecManagementPoliciesItemCreate:
		return true
	case BucketMetricSpecManagementPoliciesItemBucketMetricSpecManagementPoliciesItemDelete:
		return true
	case BucketMetricSpecManagementPoliciesItemBucketMetricSpecManagementPoliciesItemLateInitialize:
		return true
	case BucketMetricSpecManagementPoliciesItemBucketMetricSpecManagementPoliciesItemObserve:
		return true
	case BucketMetricSpecManagementPoliciesItemBucketMetricSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecProviderConfigRefPolicyResolution.
const (
	BucketMetricSpecProviderConfigRefPolicyResolutionOptional BucketMetricSpecProviderConfigRefPolicyResolution = "Optional"
	BucketMetricSpecProviderConfigRefPolicyResolutionRequired BucketMetricSpecProviderConfigRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecProviderConfigRefPolicyResolution enum.
func (e BucketMetricSpecProviderConfigRefPolicyResolution) Valid() bool {
	switch e {
	case BucketMetricSpecProviderConfigRefPolicyResolutionOptional:
		return true
	case BucketMetricSpecProviderConfigRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketMetricSpecProviderConfigRefPolicyResolve.
const (
	BucketMetricSpecProviderConfigRefPolicyResolveAlways       BucketMetricSpecProviderConfigRefPolicyResolve = "Always"
	BucketMetricSpecProviderConfigRefPolicyResolveIfNotPresent BucketMetricSpecProviderConfigRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketMetricSpecProviderConfigRefPolicyResolve enum.
func (e BucketMetricSpecProviderConfigRefPolicyResolve) Valid() bool {
	switch e {
	case BucketMetricSpecProviderConfigRefPolicyResolveAlways:
		return true
	case BucketMetricSpecProviderConfigRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// IoUpboundAwsS3V1Beta1BucketMetric BucketMetric is the Schema for the BucketMetrics API. Provides a S3 bucket metrics configuration resource.
type IoUpboundAwsS3V1Beta1BucketMetric = BucketMetric

// BucketMetricAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type BucketMetricAPIVersion string

// BucketMetricKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type BucketMetricKind string

// BucketMetricSpecDeletionPolicy DeletionPolicy specifies what will happen to the underlying external
// when this managed resource is deleted - either "Delete" or "Orphan" the
// external resource.
// This field is planned to be deprecated in favor of the ManagementPolicies
// field in a future release. Currently, both could be set independently and
// non-default values would be honored if the feature flag is enabled.
// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
type BucketMetricSpecDeletionPolicy string

// BucketMetricSpecForProviderBucketRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketMetricSpecForProviderBucketRefPolicyResolution string

// BucketMetricSpecForProviderBucketRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketMetricSpecForProviderBucketRefPolicyResolve string

// BucketMetricSpecForProviderBucketRefPolicy Policies for referencing.
type BucketMetricSpecForProviderBucketRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketMetricSpecForProviderBucketRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketMetricSpecForProviderBucketRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketMetricSpecForProviderBucketRef Reference to a Bucket in s3 to populate bucket.
type BucketMetricSpecForProviderBucketRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketMetricSpecForProviderBucketRefPolicy `json:"policy,omitempty"`
}

// BucketMetricSpecForProviderBucketSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketMetricSpecForProviderBucketSelectorPolicyResolution string

// BucketMetricSpecForProviderBucketSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketMetricSpecForProviderBucketSelectorPolicyResolve string

// BucketMetricSpecForProviderBucketSelectorPolicy Policies for selection.
type BucketMetricSpecForProviderBucketSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketMetricSpecForProviderBucketSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketMetricSpecForProviderBucketSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketMetricSpecForProviderBucketSelector Selector for a Bucket in s3 to populate bucket.
type BucketMetricSpecForProviderBucketSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *BucketMetricSpecForProviderBucketSelectorPolicy `json:"policy,omitempty"`
}

// BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolution string

// BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolve string

// BucketMetricSpecForProviderFilterItemAccessPointRefPolicy Policies for referencing.
type BucketMetricSpecForProviderFilterItemAccessPointRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketMetricSpecForProviderFilterItemAccessPointRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketMetricSpecForProviderFilterItemAccessPointRef Reference to a AccessPoint in s3control to populate accessPoint.
type BucketMetricSpecForProviderFilterItemAccessPointRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketMetricSpecForProviderFilterItemAccessPointRefPolicy `json:"policy,omitempty"`
}

// BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolution string

// BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolve string

// BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicy Policies for selection.
type BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketMetricSpecForProviderFilterItemAccessPointSelector Selector for a AccessPoint in s3control to populate accessPoint.
type BucketMetricSpecForProviderFilterItemAccessPointSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *BucketMetricSpecForProviderFilterItemAccessPointSelectorPolicy `json:"policy,omitempty"`
}

// BucketMetricSpecForProviderFilterItem defines model for .
type BucketMetricSpecForProviderFilterItem struct {
	// AccessPoint S3 Access Point ARN for filtering (singular).
	AccessPoint *string `json:"accessPoint,omitempty"`

	// AccessPointRef Reference to a AccessPoint in s3control to populate accessPoint.
	AccessPointRef *BucketMetricSpecForProviderFilterItemAccessPointRef `json:"accessPointRef,omitempty"`

	// AccessPointSelector Selector for a AccessPoint in s3control to populate accessPoint.
	AccessPointSelector *BucketMetricSpecForProviderFilterItemAccessPointSelector `json:"accessPointSelector,omitempty"`

	// Prefix Object prefix for filtering (singular).
	Prefix *string `json:"prefix,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`
}

// BucketMetricSpecForProvider defines model for .
type BucketMetricSpecForProvider struct {
	// Bucket Name of the bucket to put metric configuration.
	Bucket *string `json:"bucket,omitempty"`

	// BucketRef Reference to a Bucket in s3 to populate bucket.
	BucketRef *BucketMetricSpecForProviderBucketRef `json:"bucketRef,omitempty"`

	// BucketSelector Selector for a Bucket in s3 to populate bucket.
	BucketSelector *BucketMetricSpecForProviderBucketSelector `json:"bucketSelector,omitempty"`

	// Filter Object filtering that accepts a prefix, tags, or a logical AND of prefix and tags (documented below).
	Filter *[]BucketMetricSpecForProviderFilterItem `json:"filter,omitempty"`

	// Name Unique identifier of the metrics configuration for the bucket. Must be less than or equal to 64 characters in length.
	Name *string `json:"name,omitempty"`

	// Region Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty"`
}

// BucketMetricSpecInitProviderBucketRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketMetricSpecInitProviderBucketRefPolicyResolution string

// BucketMetricSpecInitProviderBucketRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketMetricSpecInitProviderBucketRefPolicyResolve string

// BucketMetricSpecInitProviderBucketRefPolicy Policies for referencing.
type BucketMetricSpecInitProviderBucketRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketMetricSpecInitProviderBucketRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketMetricSpecInitProviderBucketRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketMetricSpecInitProviderBucketRef Reference to a Bucket in s3 to populate bucket.
type BucketMetricSpecInitProviderBucketRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketMetricSpecInitProviderBucketRefPolicy `json:"policy,omitempty"`
}

// BucketMetricSpecInitProviderBucketSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketMetricSpecInitProviderBucketSelectorPolicyResolution string

// BucketMetricSpecInitProviderBucketSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketMetricSpecInitProviderBucketSelectorPolicyResolve string

// BucketMetricSpecInitProviderBucketSelectorPolicy Policies for selection.
type BucketMetricSpecInitProviderBucketSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketMetricSpecInitProviderBucketSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketMetricSpecInitProviderBucketSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketMetricSpecInitProviderBucketSelector Selector for a Bucket in s3 to populate bucket.
type BucketMetricSpecInitProviderBucketSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *BucketMetricSpecInitProviderBucketSelectorPolicy `json:"policy,omitempty"`
}

// BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolution string

// BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolve string

// BucketMetricSpecInitProviderFilterItemAccessPointRefPolicy Policies for referencing.
type BucketMetricSpecInitProviderFilterItemAccessPointRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketMetricSpecInitProviderFilterItemAccessPointRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketMetricSpecInitProviderFilterItemAccessPointRef Reference to a AccessPoint in s3control to populate accessPoint.
type BucketMetricSpecInitProviderFilterItemAccessPointRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketMetricSpecInitProviderFilterItemAccessPointRefPolicy `json:"policy,omitempty"`
}

// BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolution string

// BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolve string

// BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicy Policies for selection.
type BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketMetricSpecInitProviderFilterItemAccessPointSelector Selector for a AccessPoint in s3control to populate accessPoint.
type BucketMetricSpecInitProviderFilterItemAccessPointSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *BucketMetricSpecInitProviderFilterItemAccessPointSelectorPolicy `json:"policy,omitempty"`
}

// BucketMetricSpecInitProviderFilterItem defines model for .
type BucketMetricSpecInitProviderFilterItem struct {
	// AccessPoint S3 Access Point ARN for filtering (singular).
	AccessPoint *string `json:"accessPoint,omitempty"`

	// AccessPointRef Reference to a AccessPoint in s3control to populate accessPoint.
	AccessPointRef *BucketMetricSpecInitProviderFilterItemAccessPointRef `json:"accessPointRef,omitempty"`

	// AccessPointSelector Selector for a AccessPoint in s3control to populate accessPoint.
	AccessPointSelector *BucketMetricSpecInitProviderFilterItemAccessPointSelector `json:"accessPointSelector,omitempty"`

	// Prefix Object prefix for filtering (singular).
	Prefix *string `json:"prefix,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`
}

// BucketMetricSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type BucketMetricSpecInitProvider struct {
	// Bucket Name of the bucket to put metric configuration.
	Bucket *string `json:"bucket,omitempty"`

	// BucketRef Reference to a Bucket in s3 to populate bucket.
	BucketRef *BucketMetricSpecInitProviderBucketRef `json:"bucketRef,omitempty"`

	// BucketSelector Selector for a Bucket in s3 to populate bucket.
	BucketSelector *BucketMetricSpecInitProviderBucketSelector `json:"bucketSelector,omitempty"`

	// Filter Object filtering that accepts a prefix, tags, or a logical AND of prefix and tags (documented below).
	Filter *[]BucketMetricSpecInitProviderFilterItem `json:"filter,omitempty"`

	// Name Unique identifier of the metrics configuration for the bucket. Must be less than or equal to 64 characters in length.
	Name *string `json:"name,omitempty"`
}

// BucketMetricSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type BucketMetricSpecManagementPoliciesItem string

// BucketMetricSpecProviderConfigRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketMetricSpecProviderConfigRefPolicyResolution string

// BucketMetricSpecProviderConfigRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketMetricSpecProviderConfigRefPolicyResolve string

// BucketMetricSpecProviderConfigRefPolicy Policies for referencing.
type BucketMetricSpecProviderConfigRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketMetricSpecProviderConfigRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketMetricSpecProviderConfigRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketMetricSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type BucketMetricSpecProviderConfigRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketMetricSpecProviderConfigRefPolicy `json:"policy,omitempty"`
}

// BucketMetricSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type BucketMetricSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// BucketMetricSpec BucketMetricSpec defines the desired state of BucketMetric
type BucketMetricSpec struct {
	// DeletionPolicy DeletionPolicy specifies what will happen to the underlying external
	// when this managed resource is deleted - either "Delete" or "Orphan" the
	// external resource.
	// This field is planned to be deprecated in favor of the ManagementPolicies
	// field in a future release. Currently, both could be set independently and
	// non-default values would be honored if the feature flag is enabled.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	DeletionPolicy *BucketMetricSpecDeletionPolicy `json:"deletionPolicy,omitempty"`
	ForProvider    *BucketMetricSpecForProvider    `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *BucketMetricSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// This field is planned to replace the DeletionPolicy field in a future
	// release. Currently, both could be set independently and non-default
	// values would be honored if the feature flag is enabled. If both are
	// custom, the DeletionPolicy field will be ignored.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]BucketMetricSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *BucketMetricSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *BucketMetricSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// BucketMetricStatusAtProviderFilterItem defines model for .
type BucketMetricStatusAtProviderFilterItem struct {
	// AccessPoint S3 Access Point ARN for filtering (singular).
	AccessPoint *string `json:"accessPoint,omitempty"`

	// Prefix Object prefix for filtering (singular).
	Prefix *string `json:"prefix,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`
}

// BucketMetricStatusAtProvider defines model for .
type BucketMetricStatusAtProvider struct {
	// Bucket Name of the bucket to put metric configuration.
	Bucket *string `json:"bucket,omitempty"`

	// Filter Object filtering that accepts a prefix, tags, or a logical AND of prefix and tags (documented below).
	Filter *[]BucketMetricStatusAtProviderFilterItem `json:"filter,omitempty"`
	ID     *string                                   `json:"id,omitempty"`

	// Name Unique identifier of the metrics configuration for the bucket. Must be less than or equal to 64 characters in length.
	Name *string `json:"name,omitempty"`

	// Region Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty"`
}

// BucketMetricStatusConditionsItem A Condition that may apply to a resource.
type BucketMetricStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// BucketMetricStatus BucketMetricStatus defines the observed state of BucketMetric.
type BucketMetricStatus struct {
	AtProvider *BucketMetricStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]BucketMetricStatusConditionsItem `json:"conditions,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// BucketMetric BucketMetric is the Schema for the BucketMetrics API. Provides a S3 bucket metrics configuration resource.
type BucketMetric struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *BucketMetricAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *BucketMetricKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec BucketMetricSpec defines the desired state of BucketMetric
	Spec *BucketMetricSpec `json:"spec,omitempty"`

	// Status BucketMetricStatus defines the observed state of BucketMetric.
	Status *BucketMetricStatus `json:"status,omitempty"`
}

// IoUpboundAwsS3V1Beta1BucketMetricList BucketMetricList is a list of BucketMetric
type IoUpboundAwsS3V1Beta1BucketMetricList = BucketMetricList

// BucketMetricList BucketMetricList is a list of BucketMetric
type BucketMetricList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of bucketmetrics. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundAwsS3V1Beta1BucketMetric `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
