// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version v2.0.0-20260512191121-23c2b5646dfc+dirty DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for BucketObjectAPIVersion.
const (
	BucketObjectAPIVersions3AwsUpboundIoV1Beta1 BucketObjectAPIVersion = "s3.aws.upbound.io/v1beta1"
)

// Valid indicates whether the value is a known member of the BucketObjectAPIVersion enum.
func (e BucketObjectAPIVersion) Valid() bool {
	switch e {
	case BucketObjectAPIVersions3AwsUpboundIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectKind.
const (
	BucketObjectKindBucketObject BucketObjectKind = "BucketObject"
)

// Valid indicates whether the value is a known member of the BucketObjectKind enum.
func (e BucketObjectKind) Valid() bool {
	switch e {
	case BucketObjectKindBucketObject:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecDeletionPolicy.
const (
	BucketObjectSpecDeletionPolicyDelete BucketObjectSpecDeletionPolicy = "Delete"
	BucketObjectSpecDeletionPolicyOrphan BucketObjectSpecDeletionPolicy = "Orphan"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecDeletionPolicy enum.
func (e BucketObjectSpecDeletionPolicy) Valid() bool {
	switch e {
	case BucketObjectSpecDeletionPolicyDelete:
		return true
	case BucketObjectSpecDeletionPolicyOrphan:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecForProviderBucketRefPolicyResolution.
const (
	BucketObjectSpecForProviderBucketRefPolicyResolutionOptional BucketObjectSpecForProviderBucketRefPolicyResolution = "Optional"
	BucketObjectSpecForProviderBucketRefPolicyResolutionRequired BucketObjectSpecForProviderBucketRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecForProviderBucketRefPolicyResolution enum.
func (e BucketObjectSpecForProviderBucketRefPolicyResolution) Valid() bool {
	switch e {
	case BucketObjectSpecForProviderBucketRefPolicyResolutionOptional:
		return true
	case BucketObjectSpecForProviderBucketRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecForProviderBucketRefPolicyResolve.
const (
	BucketObjectSpecForProviderBucketRefPolicyResolveAlways       BucketObjectSpecForProviderBucketRefPolicyResolve = "Always"
	BucketObjectSpecForProviderBucketRefPolicyResolveIfNotPresent BucketObjectSpecForProviderBucketRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecForProviderBucketRefPolicyResolve enum.
func (e BucketObjectSpecForProviderBucketRefPolicyResolve) Valid() bool {
	switch e {
	case BucketObjectSpecForProviderBucketRefPolicyResolveAlways:
		return true
	case BucketObjectSpecForProviderBucketRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecForProviderBucketSelectorPolicyResolution.
const (
	BucketObjectSpecForProviderBucketSelectorPolicyResolutionOptional BucketObjectSpecForProviderBucketSelectorPolicyResolution = "Optional"
	BucketObjectSpecForProviderBucketSelectorPolicyResolutionRequired BucketObjectSpecForProviderBucketSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecForProviderBucketSelectorPolicyResolution enum.
func (e BucketObjectSpecForProviderBucketSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketObjectSpecForProviderBucketSelectorPolicyResolutionOptional:
		return true
	case BucketObjectSpecForProviderBucketSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecForProviderBucketSelectorPolicyResolve.
const (
	BucketObjectSpecForProviderBucketSelectorPolicyResolveAlways       BucketObjectSpecForProviderBucketSelectorPolicyResolve = "Always"
	BucketObjectSpecForProviderBucketSelectorPolicyResolveIfNotPresent BucketObjectSpecForProviderBucketSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecForProviderBucketSelectorPolicyResolve enum.
func (e BucketObjectSpecForProviderBucketSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketObjectSpecForProviderBucketSelectorPolicyResolveAlways:
		return true
	case BucketObjectSpecForProviderBucketSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecForProviderKmsKeyIDRefPolicyResolution.
const (
	BucketObjectSpecForProviderKmsKeyIDRefPolicyResolutionOptional BucketObjectSpecForProviderKmsKeyIDRefPolicyResolution = "Optional"
	BucketObjectSpecForProviderKmsKeyIDRefPolicyResolutionRequired BucketObjectSpecForProviderKmsKeyIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecForProviderKmsKeyIDRefPolicyResolution enum.
func (e BucketObjectSpecForProviderKmsKeyIDRefPolicyResolution) Valid() bool {
	switch e {
	case BucketObjectSpecForProviderKmsKeyIDRefPolicyResolutionOptional:
		return true
	case BucketObjectSpecForProviderKmsKeyIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecForProviderKmsKeyIDRefPolicyResolve.
const (
	BucketObjectSpecForProviderKmsKeyIDRefPolicyResolveAlways       BucketObjectSpecForProviderKmsKeyIDRefPolicyResolve = "Always"
	BucketObjectSpecForProviderKmsKeyIDRefPolicyResolveIfNotPresent BucketObjectSpecForProviderKmsKeyIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecForProviderKmsKeyIDRefPolicyResolve enum.
func (e BucketObjectSpecForProviderKmsKeyIDRefPolicyResolve) Valid() bool {
	switch e {
	case BucketObjectSpecForProviderKmsKeyIDRefPolicyResolveAlways:
		return true
	case BucketObjectSpecForProviderKmsKeyIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolution.
const (
	BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolutionOptional BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolution = "Optional"
	BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolutionRequired BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolution enum.
func (e BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolutionOptional:
		return true
	case BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolve.
const (
	BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolveAlways       BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolve = "Always"
	BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolveIfNotPresent BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolve enum.
func (e BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolveAlways:
		return true
	case BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecInitProviderBucketRefPolicyResolution.
const (
	BucketObjectSpecInitProviderBucketRefPolicyResolutionOptional BucketObjectSpecInitProviderBucketRefPolicyResolution = "Optional"
	BucketObjectSpecInitProviderBucketRefPolicyResolutionRequired BucketObjectSpecInitProviderBucketRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecInitProviderBucketRefPolicyResolution enum.
func (e BucketObjectSpecInitProviderBucketRefPolicyResolution) Valid() bool {
	switch e {
	case BucketObjectSpecInitProviderBucketRefPolicyResolutionOptional:
		return true
	case BucketObjectSpecInitProviderBucketRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecInitProviderBucketRefPolicyResolve.
const (
	BucketObjectSpecInitProviderBucketRefPolicyResolveAlways       BucketObjectSpecInitProviderBucketRefPolicyResolve = "Always"
	BucketObjectSpecInitProviderBucketRefPolicyResolveIfNotPresent BucketObjectSpecInitProviderBucketRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecInitProviderBucketRefPolicyResolve enum.
func (e BucketObjectSpecInitProviderBucketRefPolicyResolve) Valid() bool {
	switch e {
	case BucketObjectSpecInitProviderBucketRefPolicyResolveAlways:
		return true
	case BucketObjectSpecInitProviderBucketRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecInitProviderBucketSelectorPolicyResolution.
const (
	BucketObjectSpecInitProviderBucketSelectorPolicyResolutionOptional BucketObjectSpecInitProviderBucketSelectorPolicyResolution = "Optional"
	BucketObjectSpecInitProviderBucketSelectorPolicyResolutionRequired BucketObjectSpecInitProviderBucketSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecInitProviderBucketSelectorPolicyResolution enum.
func (e BucketObjectSpecInitProviderBucketSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketObjectSpecInitProviderBucketSelectorPolicyResolutionOptional:
		return true
	case BucketObjectSpecInitProviderBucketSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecInitProviderBucketSelectorPolicyResolve.
const (
	BucketObjectSpecInitProviderBucketSelectorPolicyResolveAlways       BucketObjectSpecInitProviderBucketSelectorPolicyResolve = "Always"
	BucketObjectSpecInitProviderBucketSelectorPolicyResolveIfNotPresent BucketObjectSpecInitProviderBucketSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecInitProviderBucketSelectorPolicyResolve enum.
func (e BucketObjectSpecInitProviderBucketSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketObjectSpecInitProviderBucketSelectorPolicyResolveAlways:
		return true
	case BucketObjectSpecInitProviderBucketSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolution.
const (
	BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolutionOptional BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolution = "Optional"
	BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolutionRequired BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolution enum.
func (e BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolution) Valid() bool {
	switch e {
	case BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolutionOptional:
		return true
	case BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolve.
const (
	BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolveAlways       BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolve = "Always"
	BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolveIfNotPresent BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolve enum.
func (e BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolve) Valid() bool {
	switch e {
	case BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolveAlways:
		return true
	case BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolution.
const (
	BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolutionOptional BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolution = "Optional"
	BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolutionRequired BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolution enum.
func (e BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolutionOptional:
		return true
	case BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolve.
const (
	BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolveAlways       BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolve = "Always"
	BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolveIfNotPresent BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolve enum.
func (e BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolveAlways:
		return true
	case BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecManagementPoliciesItem.
const (
	BucketObjectSpecManagementPoliciesItemBucketObjectSpecManagementPoliciesItem               BucketObjectSpecManagementPoliciesItem = "*"
	BucketObjectSpecManagementPoliciesItemBucketObjectSpecManagementPoliciesItemCreate         BucketObjectSpecManagementPoliciesItem = "Create"
	BucketObjectSpecManagementPoliciesItemBucketObjectSpecManagementPoliciesItemDelete         BucketObjectSpecManagementPoliciesItem = "Delete"
	BucketObjectSpecManagementPoliciesItemBucketObjectSpecManagementPoliciesItemLateInitialize BucketObjectSpecManagementPoliciesItem = "LateInitialize"
	BucketObjectSpecManagementPoliciesItemBucketObjectSpecManagementPoliciesItemObserve        BucketObjectSpecManagementPoliciesItem = "Observe"
	BucketObjectSpecManagementPoliciesItemBucketObjectSpecManagementPoliciesItemUpdate         BucketObjectSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecManagementPoliciesItem enum.
func (e BucketObjectSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case BucketObjectSpecManagementPoliciesItemBucketObjectSpecManagementPoliciesItem:
		return true
	case BucketObjectSpecManagementPoliciesItemBucketObjectSpecManagementPoliciesItemCreate:
		return true
	case BucketObjectSpecManagementPoliciesItemBucketObjectSpecManagementPoliciesItemDelete:
		return true
	case BucketObjectSpecManagementPoliciesItemBucketObjectSpecManagementPoliciesItemLateInitialize:
		return true
	case BucketObjectSpecManagementPoliciesItemBucketObjectSpecManagementPoliciesItemObserve:
		return true
	case BucketObjectSpecManagementPoliciesItemBucketObjectSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecProviderConfigRefPolicyResolution.
const (
	BucketObjectSpecProviderConfigRefPolicyResolutionOptional BucketObjectSpecProviderConfigRefPolicyResolution = "Optional"
	BucketObjectSpecProviderConfigRefPolicyResolutionRequired BucketObjectSpecProviderConfigRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecProviderConfigRefPolicyResolution enum.
func (e BucketObjectSpecProviderConfigRefPolicyResolution) Valid() bool {
	switch e {
	case BucketObjectSpecProviderConfigRefPolicyResolutionOptional:
		return true
	case BucketObjectSpecProviderConfigRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketObjectSpecProviderConfigRefPolicyResolve.
const (
	BucketObjectSpecProviderConfigRefPolicyResolveAlways       BucketObjectSpecProviderConfigRefPolicyResolve = "Always"
	BucketObjectSpecProviderConfigRefPolicyResolveIfNotPresent BucketObjectSpecProviderConfigRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketObjectSpecProviderConfigRefPolicyResolve enum.
func (e BucketObjectSpecProviderConfigRefPolicyResolve) Valid() bool {
	switch e {
	case BucketObjectSpecProviderConfigRefPolicyResolveAlways:
		return true
	case BucketObjectSpecProviderConfigRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// IoUpboundAwsS3V1Beta1BucketObject BucketObject is the Schema for the BucketObjects API. Provides an S3 object resource.
type IoUpboundAwsS3V1Beta1BucketObject = BucketObject

// BucketObjectAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type BucketObjectAPIVersion string

// BucketObjectKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type BucketObjectKind string

// BucketObjectSpecDeletionPolicy DeletionPolicy specifies what will happen to the underlying external
// when this managed resource is deleted - either "Delete" or "Orphan" the
// external resource.
// This field is planned to be deprecated in favor of the ManagementPolicies
// field in a future release. Currently, both could be set independently and
// non-default values would be honored if the feature flag is enabled.
// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
type BucketObjectSpecDeletionPolicy string

// BucketObjectSpecForProviderBucketRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketObjectSpecForProviderBucketRefPolicyResolution string

// BucketObjectSpecForProviderBucketRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketObjectSpecForProviderBucketRefPolicyResolve string

// BucketObjectSpecForProviderBucketRefPolicy Policies for referencing.
type BucketObjectSpecForProviderBucketRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketObjectSpecForProviderBucketRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketObjectSpecForProviderBucketRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketObjectSpecForProviderBucketRef Reference to a Bucket in s3 to populate bucket.
type BucketObjectSpecForProviderBucketRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketObjectSpecForProviderBucketRefPolicy `json:"policy,omitempty"`
}

// BucketObjectSpecForProviderBucketSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketObjectSpecForProviderBucketSelectorPolicyResolution string

// BucketObjectSpecForProviderBucketSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketObjectSpecForProviderBucketSelectorPolicyResolve string

// BucketObjectSpecForProviderBucketSelectorPolicy Policies for selection.
type BucketObjectSpecForProviderBucketSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketObjectSpecForProviderBucketSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketObjectSpecForProviderBucketSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketObjectSpecForProviderBucketSelector Selector for a Bucket in s3 to populate bucket.
type BucketObjectSpecForProviderBucketSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *BucketObjectSpecForProviderBucketSelectorPolicy `json:"policy,omitempty"`
}

// BucketObjectSpecForProviderKmsKeyIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketObjectSpecForProviderKmsKeyIDRefPolicyResolution string

// BucketObjectSpecForProviderKmsKeyIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketObjectSpecForProviderKmsKeyIDRefPolicyResolve string

// BucketObjectSpecForProviderKmsKeyIDRefPolicy Policies for referencing.
type BucketObjectSpecForProviderKmsKeyIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketObjectSpecForProviderKmsKeyIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketObjectSpecForProviderKmsKeyIDRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketObjectSpecForProviderKmsKeyIDRef Reference to a Key in kms to populate kmsKeyId.
type BucketObjectSpecForProviderKmsKeyIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketObjectSpecForProviderKmsKeyIDRefPolicy `json:"policy,omitempty"`
}

// BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolution string

// BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolve string

// BucketObjectSpecForProviderKmsKeyIDSelectorPolicy Policies for selection.
type BucketObjectSpecForProviderKmsKeyIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketObjectSpecForProviderKmsKeyIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketObjectSpecForProviderKmsKeyIDSelector Selector for a Key in kms to populate kmsKeyId.
type BucketObjectSpecForProviderKmsKeyIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *BucketObjectSpecForProviderKmsKeyIDSelectorPolicy `json:"policy,omitempty"`
}

// BucketObjectSpecForProvider defines model for .
type BucketObjectSpecForProvider struct {
	// ACL Canned ACL to apply. Valid values are private, public-read, public-read-write, aws-exec-read, authenticated-read, bucket-owner-read, and bucket-owner-full-control. Defaults to private.
	ACL *string `json:"acl,omitempty"`

	// Bucket Name of the bucket to put the file in. Alternatively, an S3 access point ARN can be specified.
	Bucket *string `json:"bucket,omitempty"`

	// BucketKeyEnabled Whether or not to use Amazon S3 Bucket Keys for SSE-KMS.
	BucketKeyEnabled *bool `json:"bucketKeyEnabled,omitempty"`

	// BucketRef Reference to a Bucket in s3 to populate bucket.
	BucketRef *BucketObjectSpecForProviderBucketRef `json:"bucketRef,omitempty"`

	// BucketSelector Selector for a Bucket in s3 to populate bucket.
	BucketSelector *BucketObjectSpecForProviderBucketSelector `json:"bucketSelector,omitempty"`

	// CacheControl Caching behavior along the request/reply chain Read w3c cache_control for further details.
	CacheControl *string `json:"cacheControl,omitempty"`

	// Content Literal string value to use as the object content, which will be uploaded as UTF-8-encoded text.
	Content *string `json:"content,omitempty"`

	// ContentBase64 Base64-encoded data that will be decoded and uploaded as raw bytes for the object content. This allows safely uploading non-UTF8 binary data, but is recommended only for small content such as the result of the gzipbase64 function with small text strings. For larger objects, use source to stream the content from a disk file.
	ContentBase64 *string `json:"contentBase64,omitempty"`

	// ContentDisposition Presentational information for the object. Read w3c content_disposition for further information.
	ContentDisposition *string `json:"contentDisposition,omitempty"`

	// ContentEncoding Content encodings that have been applied to the object and thus what decoding mechanisms must be applied to obtain the media-type referenced by the Content-Type header field. Read w3c content encoding for further information.
	ContentEncoding *string `json:"contentEncoding,omitempty"`

	// ContentLanguage Language the content is in e.g., en-US or en-GB.
	ContentLanguage *string `json:"contentLanguage,omitempty"`

	// ContentType Standard MIME type describing the format of the object data, e.g., application/octet-stream. All Valid MIME Types are valid for this input.
	ContentType *string `json:"contentType,omitempty"`

	// Etag Triggers updates when the value changes.11.11.11 or earlier). This attribute is not compatible with KMS encryption, kms_key_id or server_side_encryption = "aws:kms" (see source_hash instead).
	Etag *string `json:"etag,omitempty"`

	// ForceDestroy Whether to allow the object to be deleted by removing any legal hold on any object version. Default is false. This value should be set to true only if the bucket has S3 object lock enabled.
	ForceDestroy *bool `json:"forceDestroy,omitempty"`

	// Key Name of the object once it is in the bucket.
	Key *string `json:"key,omitempty"`

	// KmsKeyID ARN of the KMS Key to use for object encryption. If the S3 Bucket has server-side encryption enabled, that value will automatically be used. If referencing the aws_kms_key resource, use the arn attribute. If referencing the aws_kms_alias data source or resource, use the target_key_arn attribute.
	KmsKeyID *string `json:"kmsKeyId,omitempty"`

	// KmsKeyIDRef Reference to a Key in kms to populate kmsKeyId.
	KmsKeyIDRef *BucketObjectSpecForProviderKmsKeyIDRef `json:"kmsKeyIdRef,omitempty"`

	// KmsKeyIDSelector Selector for a Key in kms to populate kmsKeyId.
	KmsKeyIDSelector *BucketObjectSpecForProviderKmsKeyIDSelector `json:"kmsKeyIdSelector,omitempty"`

	// Metadata Map of keys/values to provision metadata (will be automatically prefixed by x-amz-meta-, note that only lowercase label are currently supported by the AWS Go API).
	Metadata *map[string]string `json:"metadata,omitempty"`

	// ObjectLockLegalHoldStatus Legal hold status that you want to apply to the specified object. Valid values are ON and OFF.
	ObjectLockLegalHoldStatus *string `json:"objectLockLegalHoldStatus,omitempty"`

	// ObjectLockMode Object lock retention mode that you want to apply to this object. Valid values are GOVERNANCE and COMPLIANCE.
	ObjectLockMode *string `json:"objectLockMode,omitempty"`

	// ObjectLockRetainUntilDate Date and time, in RFC3339 format, when this object's object lock will expire.
	ObjectLockRetainUntilDate *string `json:"objectLockRetainUntilDate,omitempty"`

	// Region Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty"`

	// ServerSideEncryption Server-side encryption of the object in S3. Valid values are "AES256" and "aws:kms".
	ServerSideEncryption *string `json:"serverSideEncryption,omitempty"`

	// Source Path to a file that will be read and uploaded as raw bytes for the object content.
	Source *string `json:"source,omitempty"`

	// SourceHash Triggers updates like etag but useful to address etag encryption limitations.11.12 or later). (The value is only stored in state and not saved by AWS.)
	SourceHash *string `json:"sourceHash,omitempty"`

	// StorageClass Storage Class for the object. Defaults to "STANDARD".
	StorageClass *string `json:"storageClass,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`

	// WebsiteRedirect Target URL for website redirect.
	WebsiteRedirect *string `json:"websiteRedirect,omitempty"`
}

// BucketObjectSpecInitProviderBucketRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketObjectSpecInitProviderBucketRefPolicyResolution string

// BucketObjectSpecInitProviderBucketRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketObjectSpecInitProviderBucketRefPolicyResolve string

// BucketObjectSpecInitProviderBucketRefPolicy Policies for referencing.
type BucketObjectSpecInitProviderBucketRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketObjectSpecInitProviderBucketRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketObjectSpecInitProviderBucketRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketObjectSpecInitProviderBucketRef Reference to a Bucket in s3 to populate bucket.
type BucketObjectSpecInitProviderBucketRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketObjectSpecInitProviderBucketRefPolicy `json:"policy,omitempty"`
}

// BucketObjectSpecInitProviderBucketSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketObjectSpecInitProviderBucketSelectorPolicyResolution string

// BucketObjectSpecInitProviderBucketSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketObjectSpecInitProviderBucketSelectorPolicyResolve string

// BucketObjectSpecInitProviderBucketSelectorPolicy Policies for selection.
type BucketObjectSpecInitProviderBucketSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketObjectSpecInitProviderBucketSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketObjectSpecInitProviderBucketSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketObjectSpecInitProviderBucketSelector Selector for a Bucket in s3 to populate bucket.
type BucketObjectSpecInitProviderBucketSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *BucketObjectSpecInitProviderBucketSelectorPolicy `json:"policy,omitempty"`
}

// BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolution string

// BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolve string

// BucketObjectSpecInitProviderKmsKeyIDRefPolicy Policies for referencing.
type BucketObjectSpecInitProviderKmsKeyIDRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketObjectSpecInitProviderKmsKeyIDRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketObjectSpecInitProviderKmsKeyIDRef Reference to a Key in kms to populate kmsKeyId.
type BucketObjectSpecInitProviderKmsKeyIDRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketObjectSpecInitProviderKmsKeyIDRefPolicy `json:"policy,omitempty"`
}

// BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolution string

// BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolve string

// BucketObjectSpecInitProviderKmsKeyIDSelectorPolicy Policies for selection.
type BucketObjectSpecInitProviderKmsKeyIDSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketObjectSpecInitProviderKmsKeyIDSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketObjectSpecInitProviderKmsKeyIDSelector Selector for a Key in kms to populate kmsKeyId.
type BucketObjectSpecInitProviderKmsKeyIDSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *BucketObjectSpecInitProviderKmsKeyIDSelectorPolicy `json:"policy,omitempty"`
}

// BucketObjectSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type BucketObjectSpecInitProvider struct {
	// ACL Canned ACL to apply. Valid values are private, public-read, public-read-write, aws-exec-read, authenticated-read, bucket-owner-read, and bucket-owner-full-control. Defaults to private.
	ACL *string `json:"acl,omitempty"`

	// Bucket Name of the bucket to put the file in. Alternatively, an S3 access point ARN can be specified.
	Bucket *string `json:"bucket,omitempty"`

	// BucketKeyEnabled Whether or not to use Amazon S3 Bucket Keys for SSE-KMS.
	BucketKeyEnabled *bool `json:"bucketKeyEnabled,omitempty"`

	// BucketRef Reference to a Bucket in s3 to populate bucket.
	BucketRef *BucketObjectSpecInitProviderBucketRef `json:"bucketRef,omitempty"`

	// BucketSelector Selector for a Bucket in s3 to populate bucket.
	BucketSelector *BucketObjectSpecInitProviderBucketSelector `json:"bucketSelector,omitempty"`

	// CacheControl Caching behavior along the request/reply chain Read w3c cache_control for further details.
	CacheControl *string `json:"cacheControl,omitempty"`

	// Content Literal string value to use as the object content, which will be uploaded as UTF-8-encoded text.
	Content *string `json:"content,omitempty"`

	// ContentBase64 Base64-encoded data that will be decoded and uploaded as raw bytes for the object content. This allows safely uploading non-UTF8 binary data, but is recommended only for small content such as the result of the gzipbase64 function with small text strings. For larger objects, use source to stream the content from a disk file.
	ContentBase64 *string `json:"contentBase64,omitempty"`

	// ContentDisposition Presentational information for the object. Read w3c content_disposition for further information.
	ContentDisposition *string `json:"contentDisposition,omitempty"`

	// ContentEncoding Content encodings that have been applied to the object and thus what decoding mechanisms must be applied to obtain the media-type referenced by the Content-Type header field. Read w3c content encoding for further information.
	ContentEncoding *string `json:"contentEncoding,omitempty"`

	// ContentLanguage Language the content is in e.g., en-US or en-GB.
	ContentLanguage *string `json:"contentLanguage,omitempty"`

	// ContentType Standard MIME type describing the format of the object data, e.g., application/octet-stream. All Valid MIME Types are valid for this input.
	ContentType *string `json:"contentType,omitempty"`

	// Etag Triggers updates when the value changes.11.11.11 or earlier). This attribute is not compatible with KMS encryption, kms_key_id or server_side_encryption = "aws:kms" (see source_hash instead).
	Etag *string `json:"etag,omitempty"`

	// ForceDestroy Whether to allow the object to be deleted by removing any legal hold on any object version. Default is false. This value should be set to true only if the bucket has S3 object lock enabled.
	ForceDestroy *bool `json:"forceDestroy,omitempty"`

	// Key Name of the object once it is in the bucket.
	Key *string `json:"key,omitempty"`

	// KmsKeyID ARN of the KMS Key to use for object encryption. If the S3 Bucket has server-side encryption enabled, that value will automatically be used. If referencing the aws_kms_key resource, use the arn attribute. If referencing the aws_kms_alias data source or resource, use the target_key_arn attribute.
	KmsKeyID *string `json:"kmsKeyId,omitempty"`

	// KmsKeyIDRef Reference to a Key in kms to populate kmsKeyId.
	KmsKeyIDRef *BucketObjectSpecInitProviderKmsKeyIDRef `json:"kmsKeyIdRef,omitempty"`

	// KmsKeyIDSelector Selector for a Key in kms to populate kmsKeyId.
	KmsKeyIDSelector *BucketObjectSpecInitProviderKmsKeyIDSelector `json:"kmsKeyIdSelector,omitempty"`

	// Metadata Map of keys/values to provision metadata (will be automatically prefixed by x-amz-meta-, note that only lowercase label are currently supported by the AWS Go API).
	Metadata *map[string]string `json:"metadata,omitempty"`

	// ObjectLockLegalHoldStatus Legal hold status that you want to apply to the specified object. Valid values are ON and OFF.
	ObjectLockLegalHoldStatus *string `json:"objectLockLegalHoldStatus,omitempty"`

	// ObjectLockMode Object lock retention mode that you want to apply to this object. Valid values are GOVERNANCE and COMPLIANCE.
	ObjectLockMode *string `json:"objectLockMode,omitempty"`

	// ObjectLockRetainUntilDate Date and time, in RFC3339 format, when this object's object lock will expire.
	ObjectLockRetainUntilDate *string `json:"objectLockRetainUntilDate,omitempty"`

	// ServerSideEncryption Server-side encryption of the object in S3. Valid values are "AES256" and "aws:kms".
	ServerSideEncryption *string `json:"serverSideEncryption,omitempty"`

	// Source Path to a file that will be read and uploaded as raw bytes for the object content.
	Source *string `json:"source,omitempty"`

	// SourceHash Triggers updates like etag but useful to address etag encryption limitations.11.12 or later). (The value is only stored in state and not saved by AWS.)
	SourceHash *string `json:"sourceHash,omitempty"`

	// StorageClass Storage Class for the object. Defaults to "STANDARD".
	StorageClass *string `json:"storageClass,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`

	// WebsiteRedirect Target URL for website redirect.
	WebsiteRedirect *string `json:"websiteRedirect,omitempty"`
}

// BucketObjectSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type BucketObjectSpecManagementPoliciesItem string

// BucketObjectSpecProviderConfigRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketObjectSpecProviderConfigRefPolicyResolution string

// BucketObjectSpecProviderConfigRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketObjectSpecProviderConfigRefPolicyResolve string

// BucketObjectSpecProviderConfigRefPolicy Policies for referencing.
type BucketObjectSpecProviderConfigRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketObjectSpecProviderConfigRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketObjectSpecProviderConfigRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketObjectSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type BucketObjectSpecProviderConfigRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketObjectSpecProviderConfigRefPolicy `json:"policy,omitempty"`
}

// BucketObjectSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type BucketObjectSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// BucketObjectSpec BucketObjectSpec defines the desired state of BucketObject
type BucketObjectSpec struct {
	// DeletionPolicy DeletionPolicy specifies what will happen to the underlying external
	// when this managed resource is deleted - either "Delete" or "Orphan" the
	// external resource.
	// This field is planned to be deprecated in favor of the ManagementPolicies
	// field in a future release. Currently, both could be set independently and
	// non-default values would be honored if the feature flag is enabled.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	DeletionPolicy *BucketObjectSpecDeletionPolicy `json:"deletionPolicy,omitempty"`
	ForProvider    *BucketObjectSpecForProvider    `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *BucketObjectSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// This field is planned to replace the DeletionPolicy field in a future
	// release. Currently, both could be set independently and non-default
	// values would be honored if the feature flag is enabled. If both are
	// custom, the DeletionPolicy field will be ignored.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]BucketObjectSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *BucketObjectSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *BucketObjectSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// BucketObjectStatusAtProvider defines model for .
type BucketObjectStatusAtProvider struct {
	// ACL Canned ACL to apply. Valid values are private, public-read, public-read-write, aws-exec-read, authenticated-read, bucket-owner-read, and bucket-owner-full-control. Defaults to private.
	ACL *string `json:"acl,omitempty"`

	// Arn ARN of the object.
	Arn *string `json:"arn,omitempty"`

	// Bucket Name of the bucket to put the file in. Alternatively, an S3 access point ARN can be specified.
	Bucket *string `json:"bucket,omitempty"`

	// BucketKeyEnabled Whether or not to use Amazon S3 Bucket Keys for SSE-KMS.
	BucketKeyEnabled *bool `json:"bucketKeyEnabled,omitempty"`

	// CacheControl Caching behavior along the request/reply chain Read w3c cache_control for further details.
	CacheControl *string `json:"cacheControl,omitempty"`

	// Content Literal string value to use as the object content, which will be uploaded as UTF-8-encoded text.
	Content *string `json:"content,omitempty"`

	// ContentBase64 Base64-encoded data that will be decoded and uploaded as raw bytes for the object content. This allows safely uploading non-UTF8 binary data, but is recommended only for small content such as the result of the gzipbase64 function with small text strings. For larger objects, use source to stream the content from a disk file.
	ContentBase64 *string `json:"contentBase64,omitempty"`

	// ContentDisposition Presentational information for the object. Read w3c content_disposition for further information.
	ContentDisposition *string `json:"contentDisposition,omitempty"`

	// ContentEncoding Content encodings that have been applied to the object and thus what decoding mechanisms must be applied to obtain the media-type referenced by the Content-Type header field. Read w3c content encoding for further information.
	ContentEncoding *string `json:"contentEncoding,omitempty"`

	// ContentLanguage Language the content is in e.g., en-US or en-GB.
	ContentLanguage *string `json:"contentLanguage,omitempty"`

	// ContentType Standard MIME type describing the format of the object data, e.g., application/octet-stream. All Valid MIME Types are valid for this input.
	ContentType *string `json:"contentType,omitempty"`

	// Etag Triggers updates when the value changes.11.11.11 or earlier). This attribute is not compatible with KMS encryption, kms_key_id or server_side_encryption = "aws:kms" (see source_hash instead).
	Etag *string `json:"etag,omitempty"`

	// ForceDestroy Whether to allow the object to be deleted by removing any legal hold on any object version. Default is false. This value should be set to true only if the bucket has S3 object lock enabled.
	ForceDestroy *bool   `json:"forceDestroy,omitempty"`
	ID           *string `json:"id,omitempty"`

	// Key Name of the object once it is in the bucket.
	Key *string `json:"key,omitempty"`

	// KmsKeyID ARN of the KMS Key to use for object encryption. If the S3 Bucket has server-side encryption enabled, that value will automatically be used. If referencing the aws_kms_key resource, use the arn attribute. If referencing the aws_kms_alias data source or resource, use the target_key_arn attribute.
	KmsKeyID *string `json:"kmsKeyId,omitempty"`

	// Metadata Map of keys/values to provision metadata (will be automatically prefixed by x-amz-meta-, note that only lowercase label are currently supported by the AWS Go API).
	Metadata *map[string]string `json:"metadata,omitempty"`

	// ObjectLockLegalHoldStatus Legal hold status that you want to apply to the specified object. Valid values are ON and OFF.
	ObjectLockLegalHoldStatus *string `json:"objectLockLegalHoldStatus,omitempty"`

	// ObjectLockMode Object lock retention mode that you want to apply to this object. Valid values are GOVERNANCE and COMPLIANCE.
	ObjectLockMode *string `json:"objectLockMode,omitempty"`

	// ObjectLockRetainUntilDate Date and time, in RFC3339 format, when this object's object lock will expire.
	ObjectLockRetainUntilDate *string `json:"objectLockRetainUntilDate,omitempty"`

	// Region Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty"`

	// ServerSideEncryption Server-side encryption of the object in S3. Valid values are "AES256" and "aws:kms".
	ServerSideEncryption *string `json:"serverSideEncryption,omitempty"`

	// Source Path to a file that will be read and uploaded as raw bytes for the object content.
	Source *string `json:"source,omitempty"`

	// SourceHash Triggers updates like etag but useful to address etag encryption limitations.11.12 or later). (The value is only stored in state and not saved by AWS.)
	SourceHash *string `json:"sourceHash,omitempty"`

	// StorageClass Storage Class for the object. Defaults to "STANDARD".
	StorageClass *string `json:"storageClass,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`

	// TagsAll Map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	TagsAll *map[string]string `json:"tagsAll,omitempty"`

	// VersionID Unique version ID value for the object, if bucket versioning is enabled.
	VersionID *string `json:"versionId,omitempty"`

	// WebsiteRedirect Target URL for website redirect.
	WebsiteRedirect *string `json:"websiteRedirect,omitempty"`
}

// BucketObjectStatusConditionsItem A Condition that may apply to a resource.
type BucketObjectStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// BucketObjectStatus BucketObjectStatus defines the observed state of BucketObject.
type BucketObjectStatus struct {
	AtProvider *BucketObjectStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]BucketObjectStatusConditionsItem `json:"conditions,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// BucketObject BucketObject is the Schema for the BucketObjects API. Provides an S3 object resource.
type BucketObject struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *BucketObjectAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *BucketObjectKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec BucketObjectSpec defines the desired state of BucketObject
	Spec *BucketObjectSpec `json:"spec,omitempty"`

	// Status BucketObjectStatus defines the observed state of BucketObject.
	Status *BucketObjectStatus `json:"status,omitempty"`
}

// IoUpboundAwsS3V1Beta1BucketObjectList BucketObjectList is a list of BucketObject
type IoUpboundAwsS3V1Beta1BucketObjectList = BucketObjectList

// BucketObjectList BucketObjectList is a list of BucketObject
type BucketObjectList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of bucketobjects. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundAwsS3V1Beta1BucketObject `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
