// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version v2.0.0-20260512191121-23c2b5646dfc+dirty DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for BucketCorsConfigurationAPIVersion.
const (
	BucketCorsConfigurationAPIVersions3AwsUpboundIoV1Beta1 BucketCorsConfigurationAPIVersion = "s3.aws.upbound.io/v1beta1"
)

// Valid indicates whether the value is a known member of the BucketCorsConfigurationAPIVersion enum.
func (e BucketCorsConfigurationAPIVersion) Valid() bool {
	switch e {
	case BucketCorsConfigurationAPIVersions3AwsUpboundIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for BucketCorsConfigurationKind.
const (
	BucketCorsConfigurationKindBucketCorsConfiguration BucketCorsConfigurationKind = "BucketCorsConfiguration"
)

// Valid indicates whether the value is a known member of the BucketCorsConfigurationKind enum.
func (e BucketCorsConfigurationKind) Valid() bool {
	switch e {
	case BucketCorsConfigurationKindBucketCorsConfiguration:
		return true
	default:
		return false
	}
}

// Defines values for BucketCorsConfigurationSpecDeletionPolicy.
const (
	BucketCorsConfigurationSpecDeletionPolicyDelete BucketCorsConfigurationSpecDeletionPolicy = "Delete"
	BucketCorsConfigurationSpecDeletionPolicyOrphan BucketCorsConfigurationSpecDeletionPolicy = "Orphan"
)

// Valid indicates whether the value is a known member of the BucketCorsConfigurationSpecDeletionPolicy enum.
func (e BucketCorsConfigurationSpecDeletionPolicy) Valid() bool {
	switch e {
	case BucketCorsConfigurationSpecDeletionPolicyDelete:
		return true
	case BucketCorsConfigurationSpecDeletionPolicyOrphan:
		return true
	default:
		return false
	}
}

// Defines values for BucketCorsConfigurationSpecForProviderBucketRefPolicyResolution.
const (
	BucketCorsConfigurationSpecForProviderBucketRefPolicyResolutionOptional BucketCorsConfigurationSpecForProviderBucketRefPolicyResolution = "Optional"
	BucketCorsConfigurationSpecForProviderBucketRefPolicyResolutionRequired BucketCorsConfigurationSpecForProviderBucketRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketCorsConfigurationSpecForProviderBucketRefPolicyResolution enum.
func (e BucketCorsConfigurationSpecForProviderBucketRefPolicyResolution) Valid() bool {
	switch e {
	case BucketCorsConfigurationSpecForProviderBucketRefPolicyResolutionOptional:
		return true
	case BucketCorsConfigurationSpecForProviderBucketRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketCorsConfigurationSpecForProviderBucketRefPolicyResolve.
const (
	BucketCorsConfigurationSpecForProviderBucketRefPolicyResolveAlways       BucketCorsConfigurationSpecForProviderBucketRefPolicyResolve = "Always"
	BucketCorsConfigurationSpecForProviderBucketRefPolicyResolveIfNotPresent BucketCorsConfigurationSpecForProviderBucketRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketCorsConfigurationSpecForProviderBucketRefPolicyResolve enum.
func (e BucketCorsConfigurationSpecForProviderBucketRefPolicyResolve) Valid() bool {
	switch e {
	case BucketCorsConfigurationSpecForProviderBucketRefPolicyResolveAlways:
		return true
	case BucketCorsConfigurationSpecForProviderBucketRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolution.
const (
	BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolutionOptional BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolution = "Optional"
	BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolutionRequired BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolution enum.
func (e BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolutionOptional:
		return true
	case BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolve.
const (
	BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolveAlways       BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolve = "Always"
	BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolveIfNotPresent BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolve enum.
func (e BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolveAlways:
		return true
	case BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolution.
const (
	BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolutionOptional BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolution = "Optional"
	BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolutionRequired BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolution enum.
func (e BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolution) Valid() bool {
	switch e {
	case BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolutionOptional:
		return true
	case BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolve.
const (
	BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolveAlways       BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolve = "Always"
	BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolveIfNotPresent BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolve enum.
func (e BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolve) Valid() bool {
	switch e {
	case BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolveAlways:
		return true
	case BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolution.
const (
	BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolutionOptional BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolution = "Optional"
	BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolutionRequired BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolution enum.
func (e BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolutionOptional:
		return true
	case BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolve.
const (
	BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolveAlways       BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolve = "Always"
	BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolveIfNotPresent BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolve enum.
func (e BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolveAlways:
		return true
	case BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketCorsConfigurationSpecManagementPoliciesItem.
const (
	BucketCorsConfigurationSpecManagementPoliciesItemBucketCorsConfigurationSpecManagementPoliciesItem               BucketCorsConfigurationSpecManagementPoliciesItem = "*"
	BucketCorsConfigurationSpecManagementPoliciesItemBucketCorsConfigurationSpecManagementPoliciesItemCreate         BucketCorsConfigurationSpecManagementPoliciesItem = "Create"
	BucketCorsConfigurationSpecManagementPoliciesItemBucketCorsConfigurationSpecManagementPoliciesItemDelete         BucketCorsConfigurationSpecManagementPoliciesItem = "Delete"
	BucketCorsConfigurationSpecManagementPoliciesItemBucketCorsConfigurationSpecManagementPoliciesItemLateInitialize BucketCorsConfigurationSpecManagementPoliciesItem = "LateInitialize"
	BucketCorsConfigurationSpecManagementPoliciesItemBucketCorsConfigurationSpecManagementPoliciesItemObserve        BucketCorsConfigurationSpecManagementPoliciesItem = "Observe"
	BucketCorsConfigurationSpecManagementPoliciesItemBucketCorsConfigurationSpecManagementPoliciesItemUpdate         BucketCorsConfigurationSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the BucketCorsConfigurationSpecManagementPoliciesItem enum.
func (e BucketCorsConfigurationSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case BucketCorsConfigurationSpecManagementPoliciesItemBucketCorsConfigurationSpecManagementPoliciesItem:
		return true
	case BucketCorsConfigurationSpecManagementPoliciesItemBucketCorsConfigurationSpecManagementPoliciesItemCreate:
		return true
	case BucketCorsConfigurationSpecManagementPoliciesItemBucketCorsConfigurationSpecManagementPoliciesItemDelete:
		return true
	case BucketCorsConfigurationSpecManagementPoliciesItemBucketCorsConfigurationSpecManagementPoliciesItemLateInitialize:
		return true
	case BucketCorsConfigurationSpecManagementPoliciesItemBucketCorsConfigurationSpecManagementPoliciesItemObserve:
		return true
	case BucketCorsConfigurationSpecManagementPoliciesItemBucketCorsConfigurationSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// Defines values for BucketCorsConfigurationSpecProviderConfigRefPolicyResolution.
const (
	BucketCorsConfigurationSpecProviderConfigRefPolicyResolutionOptional BucketCorsConfigurationSpecProviderConfigRefPolicyResolution = "Optional"
	BucketCorsConfigurationSpecProviderConfigRefPolicyResolutionRequired BucketCorsConfigurationSpecProviderConfigRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketCorsConfigurationSpecProviderConfigRefPolicyResolution enum.
func (e BucketCorsConfigurationSpecProviderConfigRefPolicyResolution) Valid() bool {
	switch e {
	case BucketCorsConfigurationSpecProviderConfigRefPolicyResolutionOptional:
		return true
	case BucketCorsConfigurationSpecProviderConfigRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketCorsConfigurationSpecProviderConfigRefPolicyResolve.
const (
	BucketCorsConfigurationSpecProviderConfigRefPolicyResolveAlways       BucketCorsConfigurationSpecProviderConfigRefPolicyResolve = "Always"
	BucketCorsConfigurationSpecProviderConfigRefPolicyResolveIfNotPresent BucketCorsConfigurationSpecProviderConfigRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketCorsConfigurationSpecProviderConfigRefPolicyResolve enum.
func (e BucketCorsConfigurationSpecProviderConfigRefPolicyResolve) Valid() bool {
	switch e {
	case BucketCorsConfigurationSpecProviderConfigRefPolicyResolveAlways:
		return true
	case BucketCorsConfigurationSpecProviderConfigRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// IoUpboundAwsS3V1Beta1BucketCorsConfiguration BucketCorsConfiguration is the Schema for the BucketCorsConfigurations API. Provides an S3 bucket CORS configuration resource.
type IoUpboundAwsS3V1Beta1BucketCorsConfiguration = BucketCorsConfiguration

// BucketCorsConfigurationAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type BucketCorsConfigurationAPIVersion string

// BucketCorsConfigurationKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type BucketCorsConfigurationKind string

// BucketCorsConfigurationSpecDeletionPolicy DeletionPolicy specifies what will happen to the underlying external
// when this managed resource is deleted - either "Delete" or "Orphan" the
// external resource.
// This field is planned to be deprecated in favor of the ManagementPolicies
// field in a future release. Currently, both could be set independently and
// non-default values would be honored if the feature flag is enabled.
// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
type BucketCorsConfigurationSpecDeletionPolicy string

// BucketCorsConfigurationSpecForProviderBucketRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketCorsConfigurationSpecForProviderBucketRefPolicyResolution string

// BucketCorsConfigurationSpecForProviderBucketRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketCorsConfigurationSpecForProviderBucketRefPolicyResolve string

// BucketCorsConfigurationSpecForProviderBucketRefPolicy Policies for referencing.
type BucketCorsConfigurationSpecForProviderBucketRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketCorsConfigurationSpecForProviderBucketRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketCorsConfigurationSpecForProviderBucketRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketCorsConfigurationSpecForProviderBucketRef Reference to a Bucket in s3 to populate bucket.
type BucketCorsConfigurationSpecForProviderBucketRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketCorsConfigurationSpecForProviderBucketRefPolicy `json:"policy,omitempty"`
}

// BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolution string

// BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolve string

// BucketCorsConfigurationSpecForProviderBucketSelectorPolicy Policies for selection.
type BucketCorsConfigurationSpecForProviderBucketSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketCorsConfigurationSpecForProviderBucketSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketCorsConfigurationSpecForProviderBucketSelector Selector for a Bucket in s3 to populate bucket.
type BucketCorsConfigurationSpecForProviderBucketSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *BucketCorsConfigurationSpecForProviderBucketSelectorPolicy `json:"policy,omitempty"`
}

// BucketCorsConfigurationSpecForProviderCorsRuleItem defines model for .
type BucketCorsConfigurationSpecForProviderCorsRuleItem struct {
	// AllowedHeaders Set of Headers that are specified in the Access-Control-Request-Headers header.
	AllowedHeaders *[]string `json:"allowedHeaders,omitempty"`

	// AllowedMethods Set of HTTP methods that you allow the origin to execute. Valid values are GET, PUT, HEAD, POST, and DELETE.
	AllowedMethods *[]string `json:"allowedMethods,omitempty"`

	// AllowedOrigins Set of origins you want customers to be able to access the bucket from.
	AllowedOrigins *[]string `json:"allowedOrigins,omitempty"`

	// ExposeHeaders Set of headers in the response that you want customers to be able to access from their applications (for example, from a JavaScript XMLHttpRequest object).
	ExposeHeaders *[]string `json:"exposeHeaders,omitempty"`

	// ID Unique identifier for the rule. The value cannot be longer than 255 characters.
	ID *string `json:"id,omitempty"`

	// MaxAgeSeconds Time in seconds that your browser is to cache the preflight response for the specified resource.
	MaxAgeSeconds *float32 `json:"maxAgeSeconds,omitempty"`
}

// BucketCorsConfigurationSpecForProvider defines model for .
type BucketCorsConfigurationSpecForProvider struct {
	// Bucket Name of the bucket.
	Bucket *string `json:"bucket,omitempty"`

	// BucketRef Reference to a Bucket in s3 to populate bucket.
	BucketRef *BucketCorsConfigurationSpecForProviderBucketRef `json:"bucketRef,omitempty"`

	// BucketSelector Selector for a Bucket in s3 to populate bucket.
	BucketSelector *BucketCorsConfigurationSpecForProviderBucketSelector `json:"bucketSelector,omitempty"`

	// CorsRule Set of origins and methods (cross-origin access that you want to allow). See below. You can configure up to 100 rules.
	CorsRule *[]BucketCorsConfigurationSpecForProviderCorsRuleItem `json:"corsRule,omitempty"`

	// ExpectedBucketOwner Account ID of the expected bucket owner.
	ExpectedBucketOwner *string `json:"expectedBucketOwner,omitempty"`

	// Region Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty"`
}

// BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolution string

// BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolve string

// BucketCorsConfigurationSpecInitProviderBucketRefPolicy Policies for referencing.
type BucketCorsConfigurationSpecInitProviderBucketRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketCorsConfigurationSpecInitProviderBucketRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketCorsConfigurationSpecInitProviderBucketRef Reference to a Bucket in s3 to populate bucket.
type BucketCorsConfigurationSpecInitProviderBucketRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketCorsConfigurationSpecInitProviderBucketRefPolicy `json:"policy,omitempty"`
}

// BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolution string

// BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolve string

// BucketCorsConfigurationSpecInitProviderBucketSelectorPolicy Policies for selection.
type BucketCorsConfigurationSpecInitProviderBucketSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketCorsConfigurationSpecInitProviderBucketSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketCorsConfigurationSpecInitProviderBucketSelector Selector for a Bucket in s3 to populate bucket.
type BucketCorsConfigurationSpecInitProviderBucketSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Policy Policies for selection.
	Policy *BucketCorsConfigurationSpecInitProviderBucketSelectorPolicy `json:"policy,omitempty"`
}

// BucketCorsConfigurationSpecInitProviderCorsRuleItem defines model for .
type BucketCorsConfigurationSpecInitProviderCorsRuleItem struct {
	// AllowedHeaders Set of Headers that are specified in the Access-Control-Request-Headers header.
	AllowedHeaders *[]string `json:"allowedHeaders,omitempty"`

	// AllowedMethods Set of HTTP methods that you allow the origin to execute. Valid values are GET, PUT, HEAD, POST, and DELETE.
	AllowedMethods *[]string `json:"allowedMethods,omitempty"`

	// AllowedOrigins Set of origins you want customers to be able to access the bucket from.
	AllowedOrigins *[]string `json:"allowedOrigins,omitempty"`

	// ExposeHeaders Set of headers in the response that you want customers to be able to access from their applications (for example, from a JavaScript XMLHttpRequest object).
	ExposeHeaders *[]string `json:"exposeHeaders,omitempty"`

	// ID Unique identifier for the rule. The value cannot be longer than 255 characters.
	ID *string `json:"id,omitempty"`

	// MaxAgeSeconds Time in seconds that your browser is to cache the preflight response for the specified resource.
	MaxAgeSeconds *float32 `json:"maxAgeSeconds,omitempty"`
}

// BucketCorsConfigurationSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type BucketCorsConfigurationSpecInitProvider struct {
	// Bucket Name of the bucket.
	Bucket *string `json:"bucket,omitempty"`

	// BucketRef Reference to a Bucket in s3 to populate bucket.
	BucketRef *BucketCorsConfigurationSpecInitProviderBucketRef `json:"bucketRef,omitempty"`

	// BucketSelector Selector for a Bucket in s3 to populate bucket.
	BucketSelector *BucketCorsConfigurationSpecInitProviderBucketSelector `json:"bucketSelector,omitempty"`

	// CorsRule Set of origins and methods (cross-origin access that you want to allow). See below. You can configure up to 100 rules.
	CorsRule *[]BucketCorsConfigurationSpecInitProviderCorsRuleItem `json:"corsRule,omitempty"`

	// ExpectedBucketOwner Account ID of the expected bucket owner.
	ExpectedBucketOwner *string `json:"expectedBucketOwner,omitempty"`
}

// BucketCorsConfigurationSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type BucketCorsConfigurationSpecManagementPoliciesItem string

// BucketCorsConfigurationSpecProviderConfigRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketCorsConfigurationSpecProviderConfigRefPolicyResolution string

// BucketCorsConfigurationSpecProviderConfigRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketCorsConfigurationSpecProviderConfigRefPolicyResolve string

// BucketCorsConfigurationSpecProviderConfigRefPolicy Policies for referencing.
type BucketCorsConfigurationSpecProviderConfigRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketCorsConfigurationSpecProviderConfigRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketCorsConfigurationSpecProviderConfigRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketCorsConfigurationSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type BucketCorsConfigurationSpecProviderConfigRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketCorsConfigurationSpecProviderConfigRefPolicy `json:"policy,omitempty"`
}

// BucketCorsConfigurationSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type BucketCorsConfigurationSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the secret.
	Namespace *string `json:"namespace,omitempty"`
}

// BucketCorsConfigurationSpec BucketCorsConfigurationSpec defines the desired state of BucketCorsConfiguration
type BucketCorsConfigurationSpec struct {
	// DeletionPolicy DeletionPolicy specifies what will happen to the underlying external
	// when this managed resource is deleted - either "Delete" or "Orphan" the
	// external resource.
	// This field is planned to be deprecated in favor of the ManagementPolicies
	// field in a future release. Currently, both could be set independently and
	// non-default values would be honored if the feature flag is enabled.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	DeletionPolicy *BucketCorsConfigurationSpecDeletionPolicy `json:"deletionPolicy,omitempty"`
	ForProvider    *BucketCorsConfigurationSpecForProvider    `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *BucketCorsConfigurationSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// This field is planned to replace the DeletionPolicy field in a future
	// release. Currently, both could be set independently and non-default
	// values would be honored if the feature flag is enabled. If both are
	// custom, the DeletionPolicy field will be ignored.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]BucketCorsConfigurationSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *BucketCorsConfigurationSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *BucketCorsConfigurationSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// BucketCorsConfigurationStatusAtProviderCorsRuleItem defines model for .
type BucketCorsConfigurationStatusAtProviderCorsRuleItem struct {
	// AllowedHeaders Set of Headers that are specified in the Access-Control-Request-Headers header.
	AllowedHeaders *[]string `json:"allowedHeaders,omitempty"`

	// AllowedMethods Set of HTTP methods that you allow the origin to execute. Valid values are GET, PUT, HEAD, POST, and DELETE.
	AllowedMethods *[]string `json:"allowedMethods,omitempty"`

	// AllowedOrigins Set of origins you want customers to be able to access the bucket from.
	AllowedOrigins *[]string `json:"allowedOrigins,omitempty"`

	// ExposeHeaders Set of headers in the response that you want customers to be able to access from their applications (for example, from a JavaScript XMLHttpRequest object).
	ExposeHeaders *[]string `json:"exposeHeaders,omitempty"`

	// ID Unique identifier for the rule. The value cannot be longer than 255 characters.
	ID *string `json:"id,omitempty"`

	// MaxAgeSeconds Time in seconds that your browser is to cache the preflight response for the specified resource.
	MaxAgeSeconds *float32 `json:"maxAgeSeconds,omitempty"`
}

// BucketCorsConfigurationStatusAtProvider defines model for .
type BucketCorsConfigurationStatusAtProvider struct {
	// Bucket Name of the bucket.
	Bucket *string `json:"bucket,omitempty"`

	// CorsRule Set of origins and methods (cross-origin access that you want to allow). See below. You can configure up to 100 rules.
	CorsRule *[]BucketCorsConfigurationStatusAtProviderCorsRuleItem `json:"corsRule,omitempty"`

	// ExpectedBucketOwner Account ID of the expected bucket owner.
	ExpectedBucketOwner *string `json:"expectedBucketOwner,omitempty"`

	// ID The bucket or bucket and expected_bucket_owner separated by a comma (,) if the latter is provided.
	ID *string `json:"id,omitempty"`

	// Region Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty"`
}

// BucketCorsConfigurationStatusConditionsItem A Condition that may apply to a resource.
type BucketCorsConfigurationStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// BucketCorsConfigurationStatus BucketCorsConfigurationStatus defines the observed state of BucketCorsConfiguration.
type BucketCorsConfigurationStatus struct {
	AtProvider *BucketCorsConfigurationStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]BucketCorsConfigurationStatusConditionsItem `json:"conditions,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// BucketCorsConfiguration BucketCorsConfiguration is the Schema for the BucketCorsConfigurations API. Provides an S3 bucket CORS configuration resource.
type BucketCorsConfiguration struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *BucketCorsConfigurationAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *BucketCorsConfigurationKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec BucketCorsConfigurationSpec defines the desired state of BucketCorsConfiguration
	Spec *BucketCorsConfigurationSpec `json:"spec,omitempty"`

	// Status BucketCorsConfigurationStatus defines the observed state of BucketCorsConfiguration.
	Status *BucketCorsConfigurationStatus `json:"status,omitempty"`
}

// IoUpboundAwsS3V1Beta1BucketCorsConfigurationList BucketCorsConfigurationList is a list of BucketCorsConfiguration
type IoUpboundAwsS3V1Beta1BucketCorsConfigurationList = BucketCorsConfigurationList

// BucketCorsConfigurationList BucketCorsConfigurationList is a list of BucketCorsConfiguration
type BucketCorsConfigurationList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of bucketcorsconfigurations. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundAwsS3V1Beta1BucketCorsConfiguration `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
