// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version v2.0.0-20260512191121-23c2b5646dfc+dirty DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for BucketLifecycleConfigurationAPIVersion.
const (
	BucketLifecycleConfigurationAPIVersions3AwsMUpboundIoV1Beta1 BucketLifecycleConfigurationAPIVersion = "s3.aws.m.upbound.io/v1beta1"
)

// Valid indicates whether the value is a known member of the BucketLifecycleConfigurationAPIVersion enum.
func (e BucketLifecycleConfigurationAPIVersion) Valid() bool {
	switch e {
	case BucketLifecycleConfigurationAPIVersions3AwsMUpboundIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for BucketLifecycleConfigurationKind.
const (
	BucketLifecycleConfigurationKindBucketLifecycleConfiguration BucketLifecycleConfigurationKind = "BucketLifecycleConfiguration"
)

// Valid indicates whether the value is a known member of the BucketLifecycleConfigurationKind enum.
func (e BucketLifecycleConfigurationKind) Valid() bool {
	switch e {
	case BucketLifecycleConfigurationKindBucketLifecycleConfiguration:
		return true
	default:
		return false
	}
}

// Defines values for BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolution.
const (
	BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolutionOptional BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolution = "Optional"
	BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolutionRequired BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolution enum.
func (e BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolution) Valid() bool {
	switch e {
	case BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolutionOptional:
		return true
	case BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolve.
const (
	BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolveAlways       BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolve = "Always"
	BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolveIfNotPresent BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolve enum.
func (e BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolve) Valid() bool {
	switch e {
	case BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolveAlways:
		return true
	case BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolution.
const (
	BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolutionOptional BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolution = "Optional"
	BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolutionRequired BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolution enum.
func (e BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolutionOptional:
		return true
	case BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolve.
const (
	BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolveAlways       BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolve = "Always"
	BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolveIfNotPresent BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolve enum.
func (e BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolveAlways:
		return true
	case BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolution.
const (
	BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolutionOptional BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolution = "Optional"
	BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolutionRequired BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolution enum.
func (e BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolution) Valid() bool {
	switch e {
	case BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolutionOptional:
		return true
	case BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolve.
const (
	BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolveAlways       BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolve = "Always"
	BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolveIfNotPresent BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolve enum.
func (e BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolve) Valid() bool {
	switch e {
	case BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolveAlways:
		return true
	case BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolution.
const (
	BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolutionOptional BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolution = "Optional"
	BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolutionRequired BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolution enum.
func (e BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolutionOptional:
		return true
	case BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolve.
const (
	BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolveAlways       BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolve = "Always"
	BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolveIfNotPresent BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolve enum.
func (e BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolveAlways:
		return true
	case BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketLifecycleConfigurationSpecManagementPoliciesItem.
const (
	BucketLifecycleConfigurationSpecManagementPoliciesItemBucketLifecycleConfigurationSpecManagementPoliciesItem               BucketLifecycleConfigurationSpecManagementPoliciesItem = "*"
	BucketLifecycleConfigurationSpecManagementPoliciesItemBucketLifecycleConfigurationSpecManagementPoliciesItemCreate         BucketLifecycleConfigurationSpecManagementPoliciesItem = "Create"
	BucketLifecycleConfigurationSpecManagementPoliciesItemBucketLifecycleConfigurationSpecManagementPoliciesItemDelete         BucketLifecycleConfigurationSpecManagementPoliciesItem = "Delete"
	BucketLifecycleConfigurationSpecManagementPoliciesItemBucketLifecycleConfigurationSpecManagementPoliciesItemLateInitialize BucketLifecycleConfigurationSpecManagementPoliciesItem = "LateInitialize"
	BucketLifecycleConfigurationSpecManagementPoliciesItemBucketLifecycleConfigurationSpecManagementPoliciesItemObserve        BucketLifecycleConfigurationSpecManagementPoliciesItem = "Observe"
	BucketLifecycleConfigurationSpecManagementPoliciesItemBucketLifecycleConfigurationSpecManagementPoliciesItemUpdate         BucketLifecycleConfigurationSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the BucketLifecycleConfigurationSpecManagementPoliciesItem enum.
func (e BucketLifecycleConfigurationSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case BucketLifecycleConfigurationSpecManagementPoliciesItemBucketLifecycleConfigurationSpecManagementPoliciesItem:
		return true
	case BucketLifecycleConfigurationSpecManagementPoliciesItemBucketLifecycleConfigurationSpecManagementPoliciesItemCreate:
		return true
	case BucketLifecycleConfigurationSpecManagementPoliciesItemBucketLifecycleConfigurationSpecManagementPoliciesItemDelete:
		return true
	case BucketLifecycleConfigurationSpecManagementPoliciesItemBucketLifecycleConfigurationSpecManagementPoliciesItemLateInitialize:
		return true
	case BucketLifecycleConfigurationSpecManagementPoliciesItemBucketLifecycleConfigurationSpecManagementPoliciesItemObserve:
		return true
	case BucketLifecycleConfigurationSpecManagementPoliciesItemBucketLifecycleConfigurationSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// IoUpboundMAwsS3V1Beta1BucketLifecycleConfiguration BucketLifecycleConfiguration is the Schema for the BucketLifecycleConfigurations API. Provides a S3 bucket lifecycle configuration resource.
type IoUpboundMAwsS3V1Beta1BucketLifecycleConfiguration = BucketLifecycleConfiguration

// BucketLifecycleConfigurationAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type BucketLifecycleConfigurationAPIVersion string

// BucketLifecycleConfigurationKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type BucketLifecycleConfigurationKind string

// BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolution string

// BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolve string

// BucketLifecycleConfigurationSpecForProviderBucketRefPolicy Policies for referencing.
type BucketLifecycleConfigurationSpecForProviderBucketRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketLifecycleConfigurationSpecForProviderBucketRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketLifecycleConfigurationSpecForProviderBucketRef Reference to a Bucket in s3 to populate bucket.
type BucketLifecycleConfigurationSpecForProviderBucketRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketLifecycleConfigurationSpecForProviderBucketRefPolicy `json:"policy,omitempty"`
}

// BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolution string

// BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolve string

// BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicy Policies for selection.
type BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketLifecycleConfigurationSpecForProviderBucketSelector Selector for a Bucket in s3 to populate bucket.
type BucketLifecycleConfigurationSpecForProviderBucketSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *BucketLifecycleConfigurationSpecForProviderBucketSelectorPolicy `json:"policy,omitempty"`
}

// BucketLifecycleConfigurationSpecForProviderRuleItemAbortIncompleteMultipartUploadItem defines model for .
type BucketLifecycleConfigurationSpecForProviderRuleItemAbortIncompleteMultipartUploadItem struct {
	// DaysAfterInitiation Number of days after which Amazon S3 aborts an incomplete multipart upload.
	DaysAfterInitiation *float32 `json:"daysAfterInitiation,omitempty"`
}

// BucketLifecycleConfigurationSpecForProviderRuleItemExpirationItem defines model for .
type BucketLifecycleConfigurationSpecForProviderRuleItemExpirationItem struct {
	// Date Date objects are transitioned to the specified storage class. The date value must be in RFC3339 full-date format e.g. 2023-08-22.
	Date *string `json:"date,omitempty"`

	// Days Number of days after creation when objects are transitioned to the specified storage class. The value must be a positive integer. If both days and date are not specified, defaults to 0. Valid values depend on storage_class, see Transition objects using Amazon S3 Lifecycle for more details.
	Days *float32 `json:"days,omitempty"`

	// ExpiredObjectDeleteMarker Indicates whether Amazon S3 will remove a delete marker with no noncurrent versions. If set to true, the delete marker will be expired; if set to false the policy takes no action.
	ExpiredObjectDeleteMarker *bool `json:"expiredObjectDeleteMarker,omitempty"`
}

// BucketLifecycleConfigurationSpecForProviderRuleItemFilterItemAndItem defines model for .
type BucketLifecycleConfigurationSpecForProviderRuleItemFilterItemAndItem struct {
	// ObjectSizeGreaterThan Minimum object size (in bytes) to which the rule applies.
	ObjectSizeGreaterThan *float32 `json:"objectSizeGreaterThan,omitempty"`

	// ObjectSizeLessThan Maximum object size (in bytes) to which the rule applies.
	ObjectSizeLessThan *float32 `json:"objectSizeLessThan,omitempty"`

	// Prefix Prefix identifying one or more objects to which the rule applies.
	Prefix *string `json:"prefix,omitempty"`

	// Tags Key-value map of resource tags.
	// All of these tags must exist in the object's tag set in order for the rule to apply.
	// If set, must contain at least one key-value pair.
	Tags *map[string]string `json:"tags,omitempty"`
}

// BucketLifecycleConfigurationSpecForProviderRuleItemFilterItemTagItem defines model for .
type BucketLifecycleConfigurationSpecForProviderRuleItemFilterItemTagItem struct {
	// Key Name of the object key.
	Key *string `json:"key,omitempty"`

	// Value Value of the tag.
	Value *string `json:"value,omitempty"`
}

// BucketLifecycleConfigurationSpecForProviderRuleItemFilterItem defines model for .
type BucketLifecycleConfigurationSpecForProviderRuleItemFilterItem struct {
	// And Configuration block used to apply a logical AND to two or more predicates. See below. The Lifecycle Rule will apply to any object matching all the predicates configured inside the and block.
	And *[]BucketLifecycleConfigurationSpecForProviderRuleItemFilterItemAndItem `json:"and,omitempty"`

	// ObjectSizeGreaterThan Minimum object size (in bytes) to which the rule applies.
	ObjectSizeGreaterThan *float32 `json:"objectSizeGreaterThan,omitempty"`

	// ObjectSizeLessThan Maximum object size (in bytes) to which the rule applies.
	ObjectSizeLessThan *float32 `json:"objectSizeLessThan,omitempty"`

	// Prefix Prefix identifying one or more objects to which the rule applies. Defaults to an empty string ("") if not specified.
	Prefix *string `json:"prefix,omitempty"`

	// Tag Configuration block for specifying a tag key and value. See below.
	Tag *[]BucketLifecycleConfigurationSpecForProviderRuleItemFilterItemTagItem `json:"tag,omitempty"`
}

// BucketLifecycleConfigurationSpecForProviderRuleItemNoncurrentVersionExpirationItem defines model for .
type BucketLifecycleConfigurationSpecForProviderRuleItemNoncurrentVersionExpirationItem struct {
	// NewerNoncurrentVersions Number of noncurrent versions Amazon S3 will retain. Must be a non-zero positive integer.
	NewerNoncurrentVersions *float32 `json:"newerNoncurrentVersions,omitempty"`

	// NoncurrentDays Number of days an object is noncurrent before Amazon S3 can perform the associated action.
	NoncurrentDays *float32 `json:"noncurrentDays,omitempty"`
}

// BucketLifecycleConfigurationSpecForProviderRuleItemNoncurrentVersionTransitionItem defines model for .
type BucketLifecycleConfigurationSpecForProviderRuleItemNoncurrentVersionTransitionItem struct {
	// NewerNoncurrentVersions Number of noncurrent versions Amazon S3 will retain. Must be a non-zero positive integer.
	NewerNoncurrentVersions *float32 `json:"newerNoncurrentVersions,omitempty"`

	// NoncurrentDays Number of days an object is noncurrent before Amazon S3 can perform the associated action.
	NoncurrentDays *float32 `json:"noncurrentDays,omitempty"`

	// StorageClass Class of storage used to store the object. Valid Values: GLACIER, STANDARD_IA, ONEZONE_IA, INTELLIGENT_TIERING, DEEP_ARCHIVE, GLACIER_IR.
	StorageClass *string `json:"storageClass,omitempty"`
}

// BucketLifecycleConfigurationSpecForProviderRuleItemTransitionItem defines model for .
type BucketLifecycleConfigurationSpecForProviderRuleItemTransitionItem struct {
	// Date Date objects are transitioned to the specified storage class. The date value must be in RFC3339 full-date format e.g. 2023-08-22.
	Date *string `json:"date,omitempty"`

	// Days Number of days after creation when objects are transitioned to the specified storage class. The value must be a positive integer. If both days and date are not specified, defaults to 0. Valid values depend on storage_class, see Transition objects using Amazon S3 Lifecycle for more details.
	Days *float32 `json:"days,omitempty"`

	// StorageClass Class of storage used to store the object. Valid Values: GLACIER, STANDARD_IA, ONEZONE_IA, INTELLIGENT_TIERING, DEEP_ARCHIVE, GLACIER_IR.
	StorageClass *string `json:"storageClass,omitempty"`
}

// BucketLifecycleConfigurationSpecForProviderRuleItem defines model for .
type BucketLifecycleConfigurationSpecForProviderRuleItem struct {
	// AbortIncompleteMultipartUpload Configuration block that specifies the days since the initiation of an incomplete multipart upload that Amazon S3 will wait before permanently removing all parts of the upload. See below.
	AbortIncompleteMultipartUpload *[]BucketLifecycleConfigurationSpecForProviderRuleItemAbortIncompleteMultipartUploadItem `json:"abortIncompleteMultipartUpload,omitempty"`

	// Expiration Configuration block that specifies the expiration for the lifecycle of the object in the form of date, days and, whether the object has a delete marker. See below.
	Expiration *[]BucketLifecycleConfigurationSpecForProviderRuleItemExpirationItem `json:"expiration,omitempty"`

	// Filter Configuration block used to identify objects that a Lifecycle Rule applies to.
	// See below.
	Filter *[]BucketLifecycleConfigurationSpecForProviderRuleItemFilterItem `json:"filter,omitempty"`

	// ID Unique identifier for the rule. The value cannot be longer than 255 characters.
	ID *string `json:"id,omitempty"`

	// NoncurrentVersionExpiration Configuration block that specifies when noncurrent object versions expire. See below.
	NoncurrentVersionExpiration *[]BucketLifecycleConfigurationSpecForProviderRuleItemNoncurrentVersionExpirationItem `json:"noncurrentVersionExpiration,omitempty"`

	// NoncurrentVersionTransition Set of configuration blocks that specify the transition rule for the lifecycle rule that describes when noncurrent objects transition to a specific storage class. See below.
	NoncurrentVersionTransition *[]BucketLifecycleConfigurationSpecForProviderRuleItemNoncurrentVersionTransitionItem `json:"noncurrentVersionTransition,omitempty"`

	// Prefix DEPRECATED Use filter instead.
	// This has been deprecated by Amazon S3.
	// Prefix identifying one or more objects to which the rule applies.
	Prefix *string `json:"prefix,omitempty"`

	// Status Whether the rule is currently being applied. Valid values: Enabled or Disabled.
	Status *string `json:"status,omitempty"`

	// Transition Set of configuration blocks that specify when an Amazon S3 object transitions to a specified storage class. See below.
	Transition *[]BucketLifecycleConfigurationSpecForProviderRuleItemTransitionItem `json:"transition,omitempty"`
}

// BucketLifecycleConfigurationSpecForProvider defines model for .
type BucketLifecycleConfigurationSpecForProvider struct {
	// Bucket Name of the source S3 bucket you want Amazon S3 to monitor.
	Bucket *string `json:"bucket,omitempty"`

	// BucketRef Reference to a Bucket in s3 to populate bucket.
	BucketRef *BucketLifecycleConfigurationSpecForProviderBucketRef `json:"bucketRef,omitempty"`

	// BucketSelector Selector for a Bucket in s3 to populate bucket.
	BucketSelector *BucketLifecycleConfigurationSpecForProviderBucketSelector `json:"bucketSelector,omitempty"`

	// ExpectedBucketOwner Account ID of the expected bucket owner. If the bucket is owned by a different account, the request will fail with an HTTP 403 (Access Denied) error.
	ExpectedBucketOwner *string `json:"expectedBucketOwner,omitempty"`

	// Region Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty"`

	// Rule List of configuration blocks describing the rules managing the replication. See below.
	Rule *[]BucketLifecycleConfigurationSpecForProviderRuleItem `json:"rule,omitempty"`

	// TransitionDefaultMinimumObjectSize The default minimum object size behavior applied to the lifecycle configuration. Valid values: all_storage_classes_128K (default), varies_by_storage_class. To customize the minimum object size for any transition you can add a filter that specifies a custom object_size_greater_than or object_size_less_than value. Custom filters always take precedence over the default transition behavior.
	TransitionDefaultMinimumObjectSize *string `json:"transitionDefaultMinimumObjectSize,omitempty"`
}

// BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolution string

// BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolve string

// BucketLifecycleConfigurationSpecInitProviderBucketRefPolicy Policies for referencing.
type BucketLifecycleConfigurationSpecInitProviderBucketRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketLifecycleConfigurationSpecInitProviderBucketRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketLifecycleConfigurationSpecInitProviderBucketRef Reference to a Bucket in s3 to populate bucket.
type BucketLifecycleConfigurationSpecInitProviderBucketRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketLifecycleConfigurationSpecInitProviderBucketRefPolicy `json:"policy,omitempty"`
}

// BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolution string

// BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolve string

// BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicy Policies for selection.
type BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketLifecycleConfigurationSpecInitProviderBucketSelector Selector for a Bucket in s3 to populate bucket.
type BucketLifecycleConfigurationSpecInitProviderBucketSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *BucketLifecycleConfigurationSpecInitProviderBucketSelectorPolicy `json:"policy,omitempty"`
}

// BucketLifecycleConfigurationSpecInitProviderRuleItemAbortIncompleteMultipartUploadItem defines model for .
type BucketLifecycleConfigurationSpecInitProviderRuleItemAbortIncompleteMultipartUploadItem struct {
	// DaysAfterInitiation Number of days after which Amazon S3 aborts an incomplete multipart upload.
	DaysAfterInitiation *float32 `json:"daysAfterInitiation,omitempty"`
}

// BucketLifecycleConfigurationSpecInitProviderRuleItemExpirationItem defines model for .
type BucketLifecycleConfigurationSpecInitProviderRuleItemExpirationItem struct {
	// Date Date objects are transitioned to the specified storage class. The date value must be in RFC3339 full-date format e.g. 2023-08-22.
	Date *string `json:"date,omitempty"`

	// Days Number of days after creation when objects are transitioned to the specified storage class. The value must be a positive integer. If both days and date are not specified, defaults to 0. Valid values depend on storage_class, see Transition objects using Amazon S3 Lifecycle for more details.
	Days *float32 `json:"days,omitempty"`

	// ExpiredObjectDeleteMarker Indicates whether Amazon S3 will remove a delete marker with no noncurrent versions. If set to true, the delete marker will be expired; if set to false the policy takes no action.
	ExpiredObjectDeleteMarker *bool `json:"expiredObjectDeleteMarker,omitempty"`
}

// BucketLifecycleConfigurationSpecInitProviderRuleItemFilterItemAndItem defines model for .
type BucketLifecycleConfigurationSpecInitProviderRuleItemFilterItemAndItem struct {
	// ObjectSizeGreaterThan Minimum object size (in bytes) to which the rule applies.
	ObjectSizeGreaterThan *float32 `json:"objectSizeGreaterThan,omitempty"`

	// ObjectSizeLessThan Maximum object size (in bytes) to which the rule applies.
	ObjectSizeLessThan *float32 `json:"objectSizeLessThan,omitempty"`

	// Prefix Prefix identifying one or more objects to which the rule applies.
	Prefix *string `json:"prefix,omitempty"`

	// Tags Key-value map of resource tags.
	// All of these tags must exist in the object's tag set in order for the rule to apply.
	// If set, must contain at least one key-value pair.
	Tags *map[string]string `json:"tags,omitempty"`
}

// BucketLifecycleConfigurationSpecInitProviderRuleItemFilterItemTagItem defines model for .
type BucketLifecycleConfigurationSpecInitProviderRuleItemFilterItemTagItem struct {
	// Key Name of the object key.
	Key *string `json:"key,omitempty"`

	// Value Value of the tag.
	Value *string `json:"value,omitempty"`
}

// BucketLifecycleConfigurationSpecInitProviderRuleItemFilterItem defines model for .
type BucketLifecycleConfigurationSpecInitProviderRuleItemFilterItem struct {
	// And Configuration block used to apply a logical AND to two or more predicates. See below. The Lifecycle Rule will apply to any object matching all the predicates configured inside the and block.
	And *[]BucketLifecycleConfigurationSpecInitProviderRuleItemFilterItemAndItem `json:"and,omitempty"`

	// ObjectSizeGreaterThan Minimum object size (in bytes) to which the rule applies.
	ObjectSizeGreaterThan *float32 `json:"objectSizeGreaterThan,omitempty"`

	// ObjectSizeLessThan Maximum object size (in bytes) to which the rule applies.
	ObjectSizeLessThan *float32 `json:"objectSizeLessThan,omitempty"`

	// Prefix Prefix identifying one or more objects to which the rule applies. Defaults to an empty string ("") if not specified.
	Prefix *string `json:"prefix,omitempty"`

	// Tag Configuration block for specifying a tag key and value. See below.
	Tag *[]BucketLifecycleConfigurationSpecInitProviderRuleItemFilterItemTagItem `json:"tag,omitempty"`
}

// BucketLifecycleConfigurationSpecInitProviderRuleItemNoncurrentVersionExpirationItem defines model for .
type BucketLifecycleConfigurationSpecInitProviderRuleItemNoncurrentVersionExpirationItem struct {
	// NewerNoncurrentVersions Number of noncurrent versions Amazon S3 will retain. Must be a non-zero positive integer.
	NewerNoncurrentVersions *float32 `json:"newerNoncurrentVersions,omitempty"`

	// NoncurrentDays Number of days an object is noncurrent before Amazon S3 can perform the associated action.
	NoncurrentDays *float32 `json:"noncurrentDays,omitempty"`
}

// BucketLifecycleConfigurationSpecInitProviderRuleItemNoncurrentVersionTransitionItem defines model for .
type BucketLifecycleConfigurationSpecInitProviderRuleItemNoncurrentVersionTransitionItem struct {
	// NewerNoncurrentVersions Number of noncurrent versions Amazon S3 will retain. Must be a non-zero positive integer.
	NewerNoncurrentVersions *float32 `json:"newerNoncurrentVersions,omitempty"`

	// NoncurrentDays Number of days an object is noncurrent before Amazon S3 can perform the associated action.
	NoncurrentDays *float32 `json:"noncurrentDays,omitempty"`

	// StorageClass Class of storage used to store the object. Valid Values: GLACIER, STANDARD_IA, ONEZONE_IA, INTELLIGENT_TIERING, DEEP_ARCHIVE, GLACIER_IR.
	StorageClass *string `json:"storageClass,omitempty"`
}

// BucketLifecycleConfigurationSpecInitProviderRuleItemTransitionItem defines model for .
type BucketLifecycleConfigurationSpecInitProviderRuleItemTransitionItem struct {
	// Date Date objects are transitioned to the specified storage class. The date value must be in RFC3339 full-date format e.g. 2023-08-22.
	Date *string `json:"date,omitempty"`

	// Days Number of days after creation when objects are transitioned to the specified storage class. The value must be a positive integer. If both days and date are not specified, defaults to 0. Valid values depend on storage_class, see Transition objects using Amazon S3 Lifecycle for more details.
	Days *float32 `json:"days,omitempty"`

	// StorageClass Class of storage used to store the object. Valid Values: GLACIER, STANDARD_IA, ONEZONE_IA, INTELLIGENT_TIERING, DEEP_ARCHIVE, GLACIER_IR.
	StorageClass *string `json:"storageClass,omitempty"`
}

// BucketLifecycleConfigurationSpecInitProviderRuleItem defines model for .
type BucketLifecycleConfigurationSpecInitProviderRuleItem struct {
	// AbortIncompleteMultipartUpload Configuration block that specifies the days since the initiation of an incomplete multipart upload that Amazon S3 will wait before permanently removing all parts of the upload. See below.
	AbortIncompleteMultipartUpload *[]BucketLifecycleConfigurationSpecInitProviderRuleItemAbortIncompleteMultipartUploadItem `json:"abortIncompleteMultipartUpload,omitempty"`

	// Expiration Configuration block that specifies the expiration for the lifecycle of the object in the form of date, days and, whether the object has a delete marker. See below.
	Expiration *[]BucketLifecycleConfigurationSpecInitProviderRuleItemExpirationItem `json:"expiration,omitempty"`

	// Filter Configuration block used to identify objects that a Lifecycle Rule applies to.
	// See below.
	Filter *[]BucketLifecycleConfigurationSpecInitProviderRuleItemFilterItem `json:"filter,omitempty"`

	// ID Unique identifier for the rule. The value cannot be longer than 255 characters.
	ID *string `json:"id,omitempty"`

	// NoncurrentVersionExpiration Configuration block that specifies when noncurrent object versions expire. See below.
	NoncurrentVersionExpiration *[]BucketLifecycleConfigurationSpecInitProviderRuleItemNoncurrentVersionExpirationItem `json:"noncurrentVersionExpiration,omitempty"`

	// NoncurrentVersionTransition Set of configuration blocks that specify the transition rule for the lifecycle rule that describes when noncurrent objects transition to a specific storage class. See below.
	NoncurrentVersionTransition *[]BucketLifecycleConfigurationSpecInitProviderRuleItemNoncurrentVersionTransitionItem `json:"noncurrentVersionTransition,omitempty"`

	// Prefix DEPRECATED Use filter instead.
	// This has been deprecated by Amazon S3.
	// Prefix identifying one or more objects to which the rule applies.
	Prefix *string `json:"prefix,omitempty"`

	// Status Whether the rule is currently being applied. Valid values: Enabled or Disabled.
	Status *string `json:"status,omitempty"`

	// Transition Set of configuration blocks that specify when an Amazon S3 object transitions to a specified storage class. See below.
	Transition *[]BucketLifecycleConfigurationSpecInitProviderRuleItemTransitionItem `json:"transition,omitempty"`
}

// BucketLifecycleConfigurationSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type BucketLifecycleConfigurationSpecInitProvider struct {
	// Bucket Name of the source S3 bucket you want Amazon S3 to monitor.
	Bucket *string `json:"bucket,omitempty"`

	// BucketRef Reference to a Bucket in s3 to populate bucket.
	BucketRef *BucketLifecycleConfigurationSpecInitProviderBucketRef `json:"bucketRef,omitempty"`

	// BucketSelector Selector for a Bucket in s3 to populate bucket.
	BucketSelector *BucketLifecycleConfigurationSpecInitProviderBucketSelector `json:"bucketSelector,omitempty"`

	// ExpectedBucketOwner Account ID of the expected bucket owner. If the bucket is owned by a different account, the request will fail with an HTTP 403 (Access Denied) error.
	ExpectedBucketOwner *string `json:"expectedBucketOwner,omitempty"`

	// Rule List of configuration blocks describing the rules managing the replication. See below.
	Rule *[]BucketLifecycleConfigurationSpecInitProviderRuleItem `json:"rule,omitempty"`

	// TransitionDefaultMinimumObjectSize The default minimum object size behavior applied to the lifecycle configuration. Valid values: all_storage_classes_128K (default), varies_by_storage_class. To customize the minimum object size for any transition you can add a filter that specifies a custom object_size_greater_than or object_size_less_than value. Custom filters always take precedence over the default transition behavior.
	TransitionDefaultMinimumObjectSize *string `json:"transitionDefaultMinimumObjectSize,omitempty"`
}

// BucketLifecycleConfigurationSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type BucketLifecycleConfigurationSpecManagementPoliciesItem string

// BucketLifecycleConfigurationSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type BucketLifecycleConfigurationSpecProviderConfigRef struct {
	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`
}

// BucketLifecycleConfigurationSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type BucketLifecycleConfigurationSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`
}

// BucketLifecycleConfigurationSpec BucketLifecycleConfigurationSpec defines the desired state of BucketLifecycleConfiguration
type BucketLifecycleConfigurationSpec struct {
	ForProvider *BucketLifecycleConfigurationSpecForProvider `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *BucketLifecycleConfigurationSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]BucketLifecycleConfigurationSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *BucketLifecycleConfigurationSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *BucketLifecycleConfigurationSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// BucketLifecycleConfigurationStatusAtProviderRuleItemAbortIncompleteMultipartUploadItem defines model for .
type BucketLifecycleConfigurationStatusAtProviderRuleItemAbortIncompleteMultipartUploadItem struct {
	// DaysAfterInitiation Number of days after which Amazon S3 aborts an incomplete multipart upload.
	DaysAfterInitiation *float32 `json:"daysAfterInitiation,omitempty"`
}

// BucketLifecycleConfigurationStatusAtProviderRuleItemExpirationItem defines model for .
type BucketLifecycleConfigurationStatusAtProviderRuleItemExpirationItem struct {
	// Date Date objects are transitioned to the specified storage class. The date value must be in RFC3339 full-date format e.g. 2023-08-22.
	Date *string `json:"date,omitempty"`

	// Days Number of days after creation when objects are transitioned to the specified storage class. The value must be a positive integer. If both days and date are not specified, defaults to 0. Valid values depend on storage_class, see Transition objects using Amazon S3 Lifecycle for more details.
	Days *float32 `json:"days,omitempty"`

	// ExpiredObjectDeleteMarker Indicates whether Amazon S3 will remove a delete marker with no noncurrent versions. If set to true, the delete marker will be expired; if set to false the policy takes no action.
	ExpiredObjectDeleteMarker *bool `json:"expiredObjectDeleteMarker,omitempty"`
}

// BucketLifecycleConfigurationStatusAtProviderRuleItemFilterItemAndItem defines model for .
type BucketLifecycleConfigurationStatusAtProviderRuleItemFilterItemAndItem struct {
	// ObjectSizeGreaterThan Minimum object size (in bytes) to which the rule applies.
	ObjectSizeGreaterThan *float32 `json:"objectSizeGreaterThan,omitempty"`

	// ObjectSizeLessThan Maximum object size (in bytes) to which the rule applies.
	ObjectSizeLessThan *float32 `json:"objectSizeLessThan,omitempty"`

	// Prefix Prefix identifying one or more objects to which the rule applies.
	Prefix *string `json:"prefix,omitempty"`

	// Tags Key-value map of resource tags.
	// All of these tags must exist in the object's tag set in order for the rule to apply.
	// If set, must contain at least one key-value pair.
	Tags *map[string]string `json:"tags,omitempty"`
}

// BucketLifecycleConfigurationStatusAtProviderRuleItemFilterItemTagItem defines model for .
type BucketLifecycleConfigurationStatusAtProviderRuleItemFilterItemTagItem struct {
	// Key Name of the object key.
	Key *string `json:"key,omitempty"`

	// Value Value of the tag.
	Value *string `json:"value,omitempty"`
}

// BucketLifecycleConfigurationStatusAtProviderRuleItemFilterItem defines model for .
type BucketLifecycleConfigurationStatusAtProviderRuleItemFilterItem struct {
	// And Configuration block used to apply a logical AND to two or more predicates. See below. The Lifecycle Rule will apply to any object matching all the predicates configured inside the and block.
	And *[]BucketLifecycleConfigurationStatusAtProviderRuleItemFilterItemAndItem `json:"and,omitempty"`

	// ObjectSizeGreaterThan Minimum object size (in bytes) to which the rule applies.
	ObjectSizeGreaterThan *float32 `json:"objectSizeGreaterThan,omitempty"`

	// ObjectSizeLessThan Maximum object size (in bytes) to which the rule applies.
	ObjectSizeLessThan *float32 `json:"objectSizeLessThan,omitempty"`

	// Prefix Prefix identifying one or more objects to which the rule applies. Defaults to an empty string ("") if not specified.
	Prefix *string `json:"prefix,omitempty"`

	// Tag Configuration block for specifying a tag key and value. See below.
	Tag *[]BucketLifecycleConfigurationStatusAtProviderRuleItemFilterItemTagItem `json:"tag,omitempty"`
}

// BucketLifecycleConfigurationStatusAtProviderRuleItemNoncurrentVersionExpirationItem defines model for .
type BucketLifecycleConfigurationStatusAtProviderRuleItemNoncurrentVersionExpirationItem struct {
	// NewerNoncurrentVersions Number of noncurrent versions Amazon S3 will retain. Must be a non-zero positive integer.
	NewerNoncurrentVersions *float32 `json:"newerNoncurrentVersions,omitempty"`

	// NoncurrentDays Number of days an object is noncurrent before Amazon S3 can perform the associated action.
	NoncurrentDays *float32 `json:"noncurrentDays,omitempty"`
}

// BucketLifecycleConfigurationStatusAtProviderRuleItemNoncurrentVersionTransitionItem defines model for .
type BucketLifecycleConfigurationStatusAtProviderRuleItemNoncurrentVersionTransitionItem struct {
	// NewerNoncurrentVersions Number of noncurrent versions Amazon S3 will retain. Must be a non-zero positive integer.
	NewerNoncurrentVersions *float32 `json:"newerNoncurrentVersions,omitempty"`

	// NoncurrentDays Number of days an object is noncurrent before Amazon S3 can perform the associated action.
	NoncurrentDays *float32 `json:"noncurrentDays,omitempty"`

	// StorageClass Class of storage used to store the object. Valid Values: GLACIER, STANDARD_IA, ONEZONE_IA, INTELLIGENT_TIERING, DEEP_ARCHIVE, GLACIER_IR.
	StorageClass *string `json:"storageClass,omitempty"`
}

// BucketLifecycleConfigurationStatusAtProviderRuleItemTransitionItem defines model for .
type BucketLifecycleConfigurationStatusAtProviderRuleItemTransitionItem struct {
	// Date Date objects are transitioned to the specified storage class. The date value must be in RFC3339 full-date format e.g. 2023-08-22.
	Date *string `json:"date,omitempty"`

	// Days Number of days after creation when objects are transitioned to the specified storage class. The value must be a positive integer. If both days and date are not specified, defaults to 0. Valid values depend on storage_class, see Transition objects using Amazon S3 Lifecycle for more details.
	Days *float32 `json:"days,omitempty"`

	// StorageClass Class of storage used to store the object. Valid Values: GLACIER, STANDARD_IA, ONEZONE_IA, INTELLIGENT_TIERING, DEEP_ARCHIVE, GLACIER_IR.
	StorageClass *string `json:"storageClass,omitempty"`
}

// BucketLifecycleConfigurationStatusAtProviderRuleItem defines model for .
type BucketLifecycleConfigurationStatusAtProviderRuleItem struct {
	// AbortIncompleteMultipartUpload Configuration block that specifies the days since the initiation of an incomplete multipart upload that Amazon S3 will wait before permanently removing all parts of the upload. See below.
	AbortIncompleteMultipartUpload *[]BucketLifecycleConfigurationStatusAtProviderRuleItemAbortIncompleteMultipartUploadItem `json:"abortIncompleteMultipartUpload,omitempty"`

	// Expiration Configuration block that specifies the expiration for the lifecycle of the object in the form of date, days and, whether the object has a delete marker. See below.
	Expiration *[]BucketLifecycleConfigurationStatusAtProviderRuleItemExpirationItem `json:"expiration,omitempty"`

	// Filter Configuration block used to identify objects that a Lifecycle Rule applies to.
	// See below.
	Filter *[]BucketLifecycleConfigurationStatusAtProviderRuleItemFilterItem `json:"filter,omitempty"`

	// ID Unique identifier for the rule. The value cannot be longer than 255 characters.
	ID *string `json:"id,omitempty"`

	// NoncurrentVersionExpiration Configuration block that specifies when noncurrent object versions expire. See below.
	NoncurrentVersionExpiration *[]BucketLifecycleConfigurationStatusAtProviderRuleItemNoncurrentVersionExpirationItem `json:"noncurrentVersionExpiration,omitempty"`

	// NoncurrentVersionTransition Set of configuration blocks that specify the transition rule for the lifecycle rule that describes when noncurrent objects transition to a specific storage class. See below.
	NoncurrentVersionTransition *[]BucketLifecycleConfigurationStatusAtProviderRuleItemNoncurrentVersionTransitionItem `json:"noncurrentVersionTransition,omitempty"`

	// Prefix DEPRECATED Use filter instead.
	// This has been deprecated by Amazon S3.
	// Prefix identifying one or more objects to which the rule applies.
	Prefix *string `json:"prefix,omitempty"`

	// Status Whether the rule is currently being applied. Valid values: Enabled or Disabled.
	Status *string `json:"status,omitempty"`

	// Transition Set of configuration blocks that specify when an Amazon S3 object transitions to a specified storage class. See below.
	Transition *[]BucketLifecycleConfigurationStatusAtProviderRuleItemTransitionItem `json:"transition,omitempty"`
}

// BucketLifecycleConfigurationStatusAtProvider defines model for .
type BucketLifecycleConfigurationStatusAtProvider struct {
	// Bucket Name of the source S3 bucket you want Amazon S3 to monitor.
	Bucket *string `json:"bucket,omitempty"`

	// ExpectedBucketOwner Account ID of the expected bucket owner. If the bucket is owned by a different account, the request will fail with an HTTP 403 (Access Denied) error.
	ExpectedBucketOwner *string `json:"expectedBucketOwner,omitempty"`

	// ID and status)
	ID *string `json:"id,omitempty"`

	// Region Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty"`

	// Rule List of configuration blocks describing the rules managing the replication. See below.
	Rule *[]BucketLifecycleConfigurationStatusAtProviderRuleItem `json:"rule,omitempty"`

	// TransitionDefaultMinimumObjectSize The default minimum object size behavior applied to the lifecycle configuration. Valid values: all_storage_classes_128K (default), varies_by_storage_class. To customize the minimum object size for any transition you can add a filter that specifies a custom object_size_greater_than or object_size_less_than value. Custom filters always take precedence over the default transition behavior.
	TransitionDefaultMinimumObjectSize *string `json:"transitionDefaultMinimumObjectSize,omitempty"`
}

// BucketLifecycleConfigurationStatusConditionsItem A Condition that may apply to a resource.
type BucketLifecycleConfigurationStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// BucketLifecycleConfigurationStatus BucketLifecycleConfigurationStatus defines the observed state of BucketLifecycleConfiguration.
type BucketLifecycleConfigurationStatus struct {
	AtProvider *BucketLifecycleConfigurationStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]BucketLifecycleConfigurationStatusConditionsItem `json:"conditions,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// BucketLifecycleConfiguration BucketLifecycleConfiguration is the Schema for the BucketLifecycleConfigurations API. Provides a S3 bucket lifecycle configuration resource.
type BucketLifecycleConfiguration struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *BucketLifecycleConfigurationAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *BucketLifecycleConfigurationKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec BucketLifecycleConfigurationSpec defines the desired state of BucketLifecycleConfiguration
	Spec *BucketLifecycleConfigurationSpec `json:"spec,omitempty"`

	// Status BucketLifecycleConfigurationStatus defines the observed state of BucketLifecycleConfiguration.
	Status *BucketLifecycleConfigurationStatus `json:"status,omitempty"`
}

// IoUpboundMAwsS3V1Beta1BucketLifecycleConfigurationList BucketLifecycleConfigurationList is a list of BucketLifecycleConfiguration
type IoUpboundMAwsS3V1Beta1BucketLifecycleConfigurationList = BucketLifecycleConfigurationList

// BucketLifecycleConfigurationList BucketLifecycleConfigurationList is a list of BucketLifecycleConfiguration
type BucketLifecycleConfigurationList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of bucketlifecycleconfigurations. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundMAwsS3V1Beta1BucketLifecycleConfiguration `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
