// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version v2.0.0-20260512191121-23c2b5646dfc+dirty DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for BucketRequestPaymentConfigurationAPIVersion.
const (
	BucketRequestPaymentConfigurationAPIVersions3AwsMUpboundIoV1Beta1 BucketRequestPaymentConfigurationAPIVersion = "s3.aws.m.upbound.io/v1beta1"
)

// Valid indicates whether the value is a known member of the BucketRequestPaymentConfigurationAPIVersion enum.
func (e BucketRequestPaymentConfigurationAPIVersion) Valid() bool {
	switch e {
	case BucketRequestPaymentConfigurationAPIVersions3AwsMUpboundIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for BucketRequestPaymentConfigurationKind.
const (
	BucketRequestPaymentConfigurationKindBucketRequestPaymentConfiguration BucketRequestPaymentConfigurationKind = "BucketRequestPaymentConfiguration"
)

// Valid indicates whether the value is a known member of the BucketRequestPaymentConfigurationKind enum.
func (e BucketRequestPaymentConfigurationKind) Valid() bool {
	switch e {
	case BucketRequestPaymentConfigurationKindBucketRequestPaymentConfiguration:
		return true
	default:
		return false
	}
}

// Defines values for BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolution.
const (
	BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolutionOptional BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolution = "Optional"
	BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolutionRequired BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolution enum.
func (e BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolution) Valid() bool {
	switch e {
	case BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolutionOptional:
		return true
	case BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolve.
const (
	BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolveAlways       BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolve = "Always"
	BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolveIfNotPresent BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolve enum.
func (e BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolve) Valid() bool {
	switch e {
	case BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolveAlways:
		return true
	case BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolution.
const (
	BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolutionOptional BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolution = "Optional"
	BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolutionRequired BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolution enum.
func (e BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolutionOptional:
		return true
	case BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolve.
const (
	BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolveAlways       BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolve = "Always"
	BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolveIfNotPresent BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolve enum.
func (e BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolveAlways:
		return true
	case BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolution.
const (
	BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolutionOptional BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolution = "Optional"
	BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolutionRequired BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolution enum.
func (e BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolution) Valid() bool {
	switch e {
	case BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolutionOptional:
		return true
	case BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolve.
const (
	BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolveAlways       BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolve = "Always"
	BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolveIfNotPresent BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolve enum.
func (e BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolve) Valid() bool {
	switch e {
	case BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolveAlways:
		return true
	case BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolution.
const (
	BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolutionOptional BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolution = "Optional"
	BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolutionRequired BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolution enum.
func (e BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolutionOptional:
		return true
	case BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolve.
const (
	BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolveAlways       BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolve = "Always"
	BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolveIfNotPresent BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolve enum.
func (e BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolveAlways:
		return true
	case BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketRequestPaymentConfigurationSpecManagementPoliciesItem.
const (
	BucketRequestPaymentConfigurationSpecManagementPoliciesItemBucketRequestPaymentConfigurationSpecManagementPoliciesItem               BucketRequestPaymentConfigurationSpecManagementPoliciesItem = "*"
	BucketRequestPaymentConfigurationSpecManagementPoliciesItemBucketRequestPaymentConfigurationSpecManagementPoliciesItemCreate         BucketRequestPaymentConfigurationSpecManagementPoliciesItem = "Create"
	BucketRequestPaymentConfigurationSpecManagementPoliciesItemBucketRequestPaymentConfigurationSpecManagementPoliciesItemDelete         BucketRequestPaymentConfigurationSpecManagementPoliciesItem = "Delete"
	BucketRequestPaymentConfigurationSpecManagementPoliciesItemBucketRequestPaymentConfigurationSpecManagementPoliciesItemLateInitialize BucketRequestPaymentConfigurationSpecManagementPoliciesItem = "LateInitialize"
	BucketRequestPaymentConfigurationSpecManagementPoliciesItemBucketRequestPaymentConfigurationSpecManagementPoliciesItemObserve        BucketRequestPaymentConfigurationSpecManagementPoliciesItem = "Observe"
	BucketRequestPaymentConfigurationSpecManagementPoliciesItemBucketRequestPaymentConfigurationSpecManagementPoliciesItemUpdate         BucketRequestPaymentConfigurationSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the BucketRequestPaymentConfigurationSpecManagementPoliciesItem enum.
func (e BucketRequestPaymentConfigurationSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case BucketRequestPaymentConfigurationSpecManagementPoliciesItemBucketRequestPaymentConfigurationSpecManagementPoliciesItem:
		return true
	case BucketRequestPaymentConfigurationSpecManagementPoliciesItemBucketRequestPaymentConfigurationSpecManagementPoliciesItemCreate:
		return true
	case BucketRequestPaymentConfigurationSpecManagementPoliciesItemBucketRequestPaymentConfigurationSpecManagementPoliciesItemDelete:
		return true
	case BucketRequestPaymentConfigurationSpecManagementPoliciesItemBucketRequestPaymentConfigurationSpecManagementPoliciesItemLateInitialize:
		return true
	case BucketRequestPaymentConfigurationSpecManagementPoliciesItemBucketRequestPaymentConfigurationSpecManagementPoliciesItemObserve:
		return true
	case BucketRequestPaymentConfigurationSpecManagementPoliciesItemBucketRequestPaymentConfigurationSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// IoUpboundMAwsS3V1Beta1BucketRequestPaymentConfiguration BucketRequestPaymentConfiguration is the Schema for the BucketRequestPaymentConfigurations API. Provides an S3 bucket request payment configuration resource.
type IoUpboundMAwsS3V1Beta1BucketRequestPaymentConfiguration = BucketRequestPaymentConfiguration

// BucketRequestPaymentConfigurationAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type BucketRequestPaymentConfigurationAPIVersion string

// BucketRequestPaymentConfigurationKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type BucketRequestPaymentConfigurationKind string

// BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolution string

// BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolve string

// BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicy Policies for referencing.
type BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketRequestPaymentConfigurationSpecForProviderBucketRef Reference to a Bucket in s3 to populate bucket.
type BucketRequestPaymentConfigurationSpecForProviderBucketRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketRequestPaymentConfigurationSpecForProviderBucketRefPolicy `json:"policy,omitempty"`
}

// BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolution string

// BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolve string

// BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicy Policies for selection.
type BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketRequestPaymentConfigurationSpecForProviderBucketSelector Selector for a Bucket in s3 to populate bucket.
type BucketRequestPaymentConfigurationSpecForProviderBucketSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *BucketRequestPaymentConfigurationSpecForProviderBucketSelectorPolicy `json:"policy,omitempty"`
}

// BucketRequestPaymentConfigurationSpecForProvider defines model for .
type BucketRequestPaymentConfigurationSpecForProvider struct {
	// Bucket Name of the bucket.
	Bucket *string `json:"bucket,omitempty"`

	// BucketRef Reference to a Bucket in s3 to populate bucket.
	BucketRef *BucketRequestPaymentConfigurationSpecForProviderBucketRef `json:"bucketRef,omitempty"`

	// BucketSelector Selector for a Bucket in s3 to populate bucket.
	BucketSelector *BucketRequestPaymentConfigurationSpecForProviderBucketSelector `json:"bucketSelector,omitempty"`

	// ExpectedBucketOwner Account ID of the expected bucket owner.
	ExpectedBucketOwner *string `json:"expectedBucketOwner,omitempty"`

	// Payer Specifies who pays for the download and request fees. Valid values: BucketOwner, Requester.
	Payer *string `json:"payer,omitempty"`

	// Region Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty"`
}

// BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolution string

// BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolve string

// BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicy Policies for referencing.
type BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketRequestPaymentConfigurationSpecInitProviderBucketRef Reference to a Bucket in s3 to populate bucket.
type BucketRequestPaymentConfigurationSpecInitProviderBucketRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketRequestPaymentConfigurationSpecInitProviderBucketRefPolicy `json:"policy,omitempty"`
}

// BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolution string

// BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolve string

// BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicy Policies for selection.
type BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketRequestPaymentConfigurationSpecInitProviderBucketSelector Selector for a Bucket in s3 to populate bucket.
type BucketRequestPaymentConfigurationSpecInitProviderBucketSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *BucketRequestPaymentConfigurationSpecInitProviderBucketSelectorPolicy `json:"policy,omitempty"`
}

// BucketRequestPaymentConfigurationSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type BucketRequestPaymentConfigurationSpecInitProvider struct {
	// Bucket Name of the bucket.
	Bucket *string `json:"bucket,omitempty"`

	// BucketRef Reference to a Bucket in s3 to populate bucket.
	BucketRef *BucketRequestPaymentConfigurationSpecInitProviderBucketRef `json:"bucketRef,omitempty"`

	// BucketSelector Selector for a Bucket in s3 to populate bucket.
	BucketSelector *BucketRequestPaymentConfigurationSpecInitProviderBucketSelector `json:"bucketSelector,omitempty"`

	// ExpectedBucketOwner Account ID of the expected bucket owner.
	ExpectedBucketOwner *string `json:"expectedBucketOwner,omitempty"`

	// Payer Specifies who pays for the download and request fees. Valid values: BucketOwner, Requester.
	Payer *string `json:"payer,omitempty"`
}

// BucketRequestPaymentConfigurationSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type BucketRequestPaymentConfigurationSpecManagementPoliciesItem string

// BucketRequestPaymentConfigurationSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type BucketRequestPaymentConfigurationSpecProviderConfigRef struct {
	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`
}

// BucketRequestPaymentConfigurationSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type BucketRequestPaymentConfigurationSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`
}

// BucketRequestPaymentConfigurationSpec BucketRequestPaymentConfigurationSpec defines the desired state of BucketRequestPaymentConfiguration
type BucketRequestPaymentConfigurationSpec struct {
	ForProvider *BucketRequestPaymentConfigurationSpecForProvider `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *BucketRequestPaymentConfigurationSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]BucketRequestPaymentConfigurationSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *BucketRequestPaymentConfigurationSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *BucketRequestPaymentConfigurationSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// BucketRequestPaymentConfigurationStatusAtProvider defines model for .
type BucketRequestPaymentConfigurationStatusAtProvider struct {
	// Bucket Name of the bucket.
	Bucket *string `json:"bucket,omitempty"`

	// ExpectedBucketOwner Account ID of the expected bucket owner.
	ExpectedBucketOwner *string `json:"expectedBucketOwner,omitempty"`

	// ID The bucket or bucket and expected_bucket_owner separated by a comma (,) if the latter is provided.
	ID *string `json:"id,omitempty"`

	// Payer Specifies who pays for the download and request fees. Valid values: BucketOwner, Requester.
	Payer *string `json:"payer,omitempty"`

	// Region Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty"`
}

// BucketRequestPaymentConfigurationStatusConditionsItem A Condition that may apply to a resource.
type BucketRequestPaymentConfigurationStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// BucketRequestPaymentConfigurationStatus BucketRequestPaymentConfigurationStatus defines the observed state of BucketRequestPaymentConfiguration.
type BucketRequestPaymentConfigurationStatus struct {
	AtProvider *BucketRequestPaymentConfigurationStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]BucketRequestPaymentConfigurationStatusConditionsItem `json:"conditions,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// BucketRequestPaymentConfiguration BucketRequestPaymentConfiguration is the Schema for the BucketRequestPaymentConfigurations API. Provides an S3 bucket request payment configuration resource.
type BucketRequestPaymentConfiguration struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *BucketRequestPaymentConfigurationAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *BucketRequestPaymentConfigurationKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec BucketRequestPaymentConfigurationSpec defines the desired state of BucketRequestPaymentConfiguration
	Spec *BucketRequestPaymentConfigurationSpec `json:"spec,omitempty"`

	// Status BucketRequestPaymentConfigurationStatus defines the observed state of BucketRequestPaymentConfiguration.
	Status *BucketRequestPaymentConfigurationStatus `json:"status,omitempty"`
}

// IoUpboundMAwsS3V1Beta1BucketRequestPaymentConfigurationList BucketRequestPaymentConfigurationList is a list of BucketRequestPaymentConfiguration
type IoUpboundMAwsS3V1Beta1BucketRequestPaymentConfigurationList = BucketRequestPaymentConfigurationList

// BucketRequestPaymentConfigurationList BucketRequestPaymentConfigurationList is a list of BucketRequestPaymentConfiguration
type BucketRequestPaymentConfigurationList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of bucketrequestpaymentconfigurations. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundMAwsS3V1Beta1BucketRequestPaymentConfiguration `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
