// Package v1beta1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version v2.0.0-20260512191121-23c2b5646dfc+dirty DO NOT EDIT.
package v1beta1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for BucketAnalyticsConfigurationAPIVersion.
const (
	BucketAnalyticsConfigurationAPIVersions3AwsMUpboundIoV1Beta1 BucketAnalyticsConfigurationAPIVersion = "s3.aws.m.upbound.io/v1beta1"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationAPIVersion enum.
func (e BucketAnalyticsConfigurationAPIVersion) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationAPIVersions3AwsMUpboundIoV1Beta1:
		return true
	default:
		return false
	}
}

// Defines values for BucketAnalyticsConfigurationKind.
const (
	BucketAnalyticsConfigurationKindBucketAnalyticsConfiguration BucketAnalyticsConfigurationKind = "BucketAnalyticsConfiguration"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationKind enum.
func (e BucketAnalyticsConfigurationKind) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationKindBucketAnalyticsConfiguration:
		return true
	default:
		return false
	}
}

// Defines values for BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolution.
const (
	BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolutionOptional BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolution = "Optional"
	BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolutionRequired BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolution enum.
func (e BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolution) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolutionOptional:
		return true
	case BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolve.
const (
	BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolveAlways       BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolve = "Always"
	BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolveIfNotPresent BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolve enum.
func (e BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolve) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolveAlways:
		return true
	case BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolution.
const (
	BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolutionOptional BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolution = "Optional"
	BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolutionRequired BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolution enum.
func (e BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolutionOptional:
		return true
	case BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolve.
const (
	BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolveAlways       BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolve = "Always"
	BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolveIfNotPresent BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolve enum.
func (e BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolveAlways:
		return true
	case BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolution.
const (
	BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolutionOptional BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolution = "Optional"
	BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolutionRequired BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolution enum.
func (e BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolution) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolutionOptional:
		return true
	case BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolve.
const (
	BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolveAlways       BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolve = "Always"
	BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolveIfNotPresent BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolve enum.
func (e BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolve) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolveAlways:
		return true
	case BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolution.
const (
	BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolutionOptional BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolution = "Optional"
	BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolutionRequired BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolution enum.
func (e BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolutionOptional:
		return true
	case BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolve.
const (
	BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolveAlways       BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolve = "Always"
	BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolveIfNotPresent BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolve enum.
func (e BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolveAlways:
		return true
	case BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolution.
const (
	BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolutionOptional BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolution = "Optional"
	BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolutionRequired BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolution enum.
func (e BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolution) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolutionOptional:
		return true
	case BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolve.
const (
	BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolveAlways       BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolve = "Always"
	BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolveIfNotPresent BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolve enum.
func (e BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolve) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolveAlways:
		return true
	case BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolution.
const (
	BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolutionOptional BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolution = "Optional"
	BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolutionRequired BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolution enum.
func (e BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolutionOptional:
		return true
	case BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolve.
const (
	BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolveAlways       BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolve = "Always"
	BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolveIfNotPresent BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolve enum.
func (e BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolveAlways:
		return true
	case BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolution.
const (
	BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolutionOptional BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolution = "Optional"
	BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolutionRequired BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolution enum.
func (e BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolution) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolutionOptional:
		return true
	case BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolve.
const (
	BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolveAlways       BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolve = "Always"
	BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolveIfNotPresent BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolve enum.
func (e BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolve) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolveAlways:
		return true
	case BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolution.
const (
	BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolutionOptional BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolution = "Optional"
	BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolutionRequired BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolution = "Required"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolution enum.
func (e BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolution) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolutionOptional:
		return true
	case BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolutionRequired:
		return true
	default:
		return false
	}
}

// Defines values for BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolve.
const (
	BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolveAlways       BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolve = "Always"
	BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolveIfNotPresent BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolve = "IfNotPresent"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolve enum.
func (e BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolve) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolveAlways:
		return true
	case BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolveIfNotPresent:
		return true
	default:
		return false
	}
}

// Defines values for BucketAnalyticsConfigurationSpecManagementPoliciesItem.
const (
	BucketAnalyticsConfigurationSpecManagementPoliciesItemBucketAnalyticsConfigurationSpecManagementPoliciesItem               BucketAnalyticsConfigurationSpecManagementPoliciesItem = "*"
	BucketAnalyticsConfigurationSpecManagementPoliciesItemBucketAnalyticsConfigurationSpecManagementPoliciesItemCreate         BucketAnalyticsConfigurationSpecManagementPoliciesItem = "Create"
	BucketAnalyticsConfigurationSpecManagementPoliciesItemBucketAnalyticsConfigurationSpecManagementPoliciesItemDelete         BucketAnalyticsConfigurationSpecManagementPoliciesItem = "Delete"
	BucketAnalyticsConfigurationSpecManagementPoliciesItemBucketAnalyticsConfigurationSpecManagementPoliciesItemLateInitialize BucketAnalyticsConfigurationSpecManagementPoliciesItem = "LateInitialize"
	BucketAnalyticsConfigurationSpecManagementPoliciesItemBucketAnalyticsConfigurationSpecManagementPoliciesItemObserve        BucketAnalyticsConfigurationSpecManagementPoliciesItem = "Observe"
	BucketAnalyticsConfigurationSpecManagementPoliciesItemBucketAnalyticsConfigurationSpecManagementPoliciesItemUpdate         BucketAnalyticsConfigurationSpecManagementPoliciesItem = "Update"
)

// Valid indicates whether the value is a known member of the BucketAnalyticsConfigurationSpecManagementPoliciesItem enum.
func (e BucketAnalyticsConfigurationSpecManagementPoliciesItem) Valid() bool {
	switch e {
	case BucketAnalyticsConfigurationSpecManagementPoliciesItemBucketAnalyticsConfigurationSpecManagementPoliciesItem:
		return true
	case BucketAnalyticsConfigurationSpecManagementPoliciesItemBucketAnalyticsConfigurationSpecManagementPoliciesItemCreate:
		return true
	case BucketAnalyticsConfigurationSpecManagementPoliciesItemBucketAnalyticsConfigurationSpecManagementPoliciesItemDelete:
		return true
	case BucketAnalyticsConfigurationSpecManagementPoliciesItemBucketAnalyticsConfigurationSpecManagementPoliciesItemLateInitialize:
		return true
	case BucketAnalyticsConfigurationSpecManagementPoliciesItemBucketAnalyticsConfigurationSpecManagementPoliciesItemObserve:
		return true
	case BucketAnalyticsConfigurationSpecManagementPoliciesItemBucketAnalyticsConfigurationSpecManagementPoliciesItemUpdate:
		return true
	default:
		return false
	}
}

// IoUpboundMAwsS3V1Beta1BucketAnalyticsConfiguration BucketAnalyticsConfiguration is the Schema for the BucketAnalyticsConfigurations API. Provides a S3 bucket analytics configuration resource.
type IoUpboundMAwsS3V1Beta1BucketAnalyticsConfiguration = BucketAnalyticsConfiguration

// BucketAnalyticsConfigurationAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type BucketAnalyticsConfigurationAPIVersion string

// BucketAnalyticsConfigurationKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type BucketAnalyticsConfigurationKind string

// BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolution string

// BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolve string

// BucketAnalyticsConfigurationSpecForProviderBucketRefPolicy Policies for referencing.
type BucketAnalyticsConfigurationSpecForProviderBucketRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketAnalyticsConfigurationSpecForProviderBucketRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketAnalyticsConfigurationSpecForProviderBucketRef Reference to a Bucket in s3 to populate bucket.
type BucketAnalyticsConfigurationSpecForProviderBucketRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketAnalyticsConfigurationSpecForProviderBucketRefPolicy `json:"policy,omitempty"`
}

// BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolution string

// BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolve string

// BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicy Policies for selection.
type BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketAnalyticsConfigurationSpecForProviderBucketSelector Selector for a Bucket in s3 to populate bucket.
type BucketAnalyticsConfigurationSpecForProviderBucketSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *BucketAnalyticsConfigurationSpecForProviderBucketSelectorPolicy `json:"policy,omitempty"`
}

// BucketAnalyticsConfigurationSpecForProviderFilter Object filtering that accepts a prefix, tags, or a logical AND of prefix and tags (documented below).
type BucketAnalyticsConfigurationSpecForProviderFilter struct {
	// Prefix Object prefix for filtering.
	Prefix *string `json:"prefix,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`
}

// BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolution string

// BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolve string

// BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicy Policies for referencing.
type BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRef Reference to a Bucket in s3 to populate bucketArn.
type BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicy `json:"policy,omitempty"`
}

// BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolution string

// BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolve string

// BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicy Policies for selection.
type BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelector Selector for a Bucket in s3 to populate bucketArn.
type BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicy `json:"policy,omitempty"`
}

// BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestination Analytics data export currently only supports an S3 bucket destination (documented below).
type BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestination struct {
	// BucketAccountID Account ID that owns the destination bucket.
	BucketAccountID *string `json:"bucketAccountId,omitempty"`

	// BucketArn ARN of the destination bucket.
	BucketArn *string `json:"bucketArn,omitempty"`

	// BucketArnRef Reference to a Bucket in s3 to populate bucketArn.
	BucketArnRef *BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRef `json:"bucketArnRef,omitempty"`

	// BucketArnSelector Selector for a Bucket in s3 to populate bucketArn.
	BucketArnSelector *BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelector `json:"bucketArnSelector,omitempty"`

	// Format Output format of exported analytics data. Allowed values: CSV. Default value: CSV.
	Format *string `json:"format,omitempty"`

	// Prefix Object prefix for filtering.
	Prefix *string `json:"prefix,omitempty"`
}

// BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestination Specifies the destination for the exported analytics data (documented below).
type BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestination struct {
	// S3BucketDestination Analytics data export currently only supports an S3 bucket destination (documented below).
	S3BucketDestination *BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestinationS3BucketDestination `json:"s3BucketDestination,omitempty"`
}

// BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExport Data export configuration (documented below).
type BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExport struct {
	// Destination Specifies the destination for the exported analytics data (documented below).
	Destination *BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExportDestination `json:"destination,omitempty"`

	// OutputSchemaVersion Schema version of exported analytics data. Allowed values: V_1. Default value: V_1.
	OutputSchemaVersion *string `json:"outputSchemaVersion,omitempty"`
}

// BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysis Configuration for the analytics data export (documented below).
type BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysis struct {
	// DataExport Data export configuration (documented below).
	DataExport *BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysisDataExport `json:"dataExport,omitempty"`
}

// BucketAnalyticsConfigurationSpecForProvider defines model for .
type BucketAnalyticsConfigurationSpecForProvider struct {
	// Bucket Name of the bucket this analytics configuration is associated with.
	Bucket *string `json:"bucket,omitempty"`

	// BucketRef Reference to a Bucket in s3 to populate bucket.
	BucketRef *BucketAnalyticsConfigurationSpecForProviderBucketRef `json:"bucketRef,omitempty"`

	// BucketSelector Selector for a Bucket in s3 to populate bucket.
	BucketSelector *BucketAnalyticsConfigurationSpecForProviderBucketSelector `json:"bucketSelector,omitempty"`

	// Filter Object filtering that accepts a prefix, tags, or a logical AND of prefix and tags (documented below).
	Filter *BucketAnalyticsConfigurationSpecForProviderFilter `json:"filter,omitempty"`

	// Name Unique identifier of the analytics configuration for the bucket.
	Name *string `json:"name,omitempty"`

	// Region Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty"`

	// StorageClassAnalysis Configuration for the analytics data export (documented below).
	StorageClassAnalysis *BucketAnalyticsConfigurationSpecForProviderStorageClassAnalysis `json:"storageClassAnalysis,omitempty"`
}

// BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolution string

// BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolve string

// BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicy Policies for referencing.
type BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketAnalyticsConfigurationSpecInitProviderBucketRef Reference to a Bucket in s3 to populate bucket.
type BucketAnalyticsConfigurationSpecInitProviderBucketRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketAnalyticsConfigurationSpecInitProviderBucketRefPolicy `json:"policy,omitempty"`
}

// BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolution string

// BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolve string

// BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicy Policies for selection.
type BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketAnalyticsConfigurationSpecInitProviderBucketSelector Selector for a Bucket in s3 to populate bucket.
type BucketAnalyticsConfigurationSpecInitProviderBucketSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *BucketAnalyticsConfigurationSpecInitProviderBucketSelectorPolicy `json:"policy,omitempty"`
}

// BucketAnalyticsConfigurationSpecInitProviderFilter Object filtering that accepts a prefix, tags, or a logical AND of prefix and tags (documented below).
type BucketAnalyticsConfigurationSpecInitProviderFilter struct {
	// Prefix Object prefix for filtering.
	Prefix *string `json:"prefix,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`
}

// BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolution string

// BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolve string

// BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicy Policies for referencing.
type BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicyResolve `json:"resolve,omitempty"`
}

// BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRef Reference to a Bucket in s3 to populate bucketArn.
type BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRef struct {
	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`

	// Namespace Namespace of the referenced object
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for referencing.
	Policy *BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRefPolicy `json:"policy,omitempty"`
}

// BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolution Resolution specifies whether resolution of this reference is required.
// The default is 'Required', which means the reconcile will fail if the
// reference cannot be resolved. 'Optional' means this reference will be
// a no-op if it cannot be resolved.
type BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolution string

// BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolve Resolve specifies when this reference should be resolved. The default
// is 'IfNotPresent', which will attempt to resolve the reference only when
// the corresponding field is not present. Use 'Always' to resolve the
// reference on every reconcile.
type BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolve string

// BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicy Policies for selection.
type BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicy struct {
	// Resolution Resolution specifies whether resolution of this reference is required.
	// The default is 'Required', which means the reconcile will fail if the
	// reference cannot be resolved. 'Optional' means this reference will be
	// a no-op if it cannot be resolved.
	Resolution *BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolution `json:"resolution,omitempty"`

	// Resolve Resolve specifies when this reference should be resolved. The default
	// is 'IfNotPresent', which will attempt to resolve the reference only when
	// the corresponding field is not present. Use 'Always' to resolve the
	// reference on every reconcile.
	Resolve *BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicyResolve `json:"resolve,omitempty"`
}

// BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelector Selector for a Bucket in s3 to populate bucketArn.
type BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelector struct {
	// MatchControllerRef MatchControllerRef ensures an object with the same controller reference
	// as the selecting object is selected.
	MatchControllerRef *bool `json:"matchControllerRef,omitempty"`

	// MatchLabels MatchLabels ensures an object with matching labels is selected.
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`

	// Namespace Namespace for the selector
	Namespace *string `json:"namespace,omitempty"`

	// Policy Policies for selection.
	Policy *BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelectorPolicy `json:"policy,omitempty"`
}

// BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestination Analytics data export currently only supports an S3 bucket destination (documented below).
type BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestination struct {
	// BucketAccountID Account ID that owns the destination bucket.
	BucketAccountID *string `json:"bucketAccountId,omitempty"`

	// BucketArn ARN of the destination bucket.
	BucketArn *string `json:"bucketArn,omitempty"`

	// BucketArnRef Reference to a Bucket in s3 to populate bucketArn.
	BucketArnRef *BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnRef `json:"bucketArnRef,omitempty"`

	// BucketArnSelector Selector for a Bucket in s3 to populate bucketArn.
	BucketArnSelector *BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestinationBucketArnSelector `json:"bucketArnSelector,omitempty"`

	// Format Output format of exported analytics data. Allowed values: CSV. Default value: CSV.
	Format *string `json:"format,omitempty"`

	// Prefix Object prefix for filtering.
	Prefix *string `json:"prefix,omitempty"`
}

// BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestination Specifies the destination for the exported analytics data (documented below).
type BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestination struct {
	// S3BucketDestination Analytics data export currently only supports an S3 bucket destination (documented below).
	S3BucketDestination *BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestinationS3BucketDestination `json:"s3BucketDestination,omitempty"`
}

// BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExport Data export configuration (documented below).
type BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExport struct {
	// Destination Specifies the destination for the exported analytics data (documented below).
	Destination *BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExportDestination `json:"destination,omitempty"`

	// OutputSchemaVersion Schema version of exported analytics data. Allowed values: V_1. Default value: V_1.
	OutputSchemaVersion *string `json:"outputSchemaVersion,omitempty"`
}

// BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysis Configuration for the analytics data export (documented below).
type BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysis struct {
	// DataExport Data export configuration (documented below).
	DataExport *BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysisDataExport `json:"dataExport,omitempty"`
}

// BucketAnalyticsConfigurationSpecInitProvider THIS IS A BETA FIELD. It will be honored
// unless the Management Policies feature flag is disabled.
// InitProvider holds the same fields as ForProvider, with the exception
// of Identifier and other resource reference fields. The fields that are
// in InitProvider are merged into ForProvider when the resource is created.
// The same fields are also added to the terraform ignore_changes hook, to
// avoid updating them after creation. This is useful for fields that are
// required on creation, but we do not desire to update them after creation,
// for example because of an external controller is managing them, like an
// autoscaler.
type BucketAnalyticsConfigurationSpecInitProvider struct {
	// Bucket Name of the bucket this analytics configuration is associated with.
	Bucket *string `json:"bucket,omitempty"`

	// BucketRef Reference to a Bucket in s3 to populate bucket.
	BucketRef *BucketAnalyticsConfigurationSpecInitProviderBucketRef `json:"bucketRef,omitempty"`

	// BucketSelector Selector for a Bucket in s3 to populate bucket.
	BucketSelector *BucketAnalyticsConfigurationSpecInitProviderBucketSelector `json:"bucketSelector,omitempty"`

	// Filter Object filtering that accepts a prefix, tags, or a logical AND of prefix and tags (documented below).
	Filter *BucketAnalyticsConfigurationSpecInitProviderFilter `json:"filter,omitempty"`

	// Name Unique identifier of the analytics configuration for the bucket.
	Name *string `json:"name,omitempty"`

	// StorageClassAnalysis Configuration for the analytics data export (documented below).
	StorageClassAnalysis *BucketAnalyticsConfigurationSpecInitProviderStorageClassAnalysis `json:"storageClassAnalysis,omitempty"`
}

// BucketAnalyticsConfigurationSpecManagementPoliciesItem A ManagementAction represents an action that the Crossplane controllers
// can take on an external resource.
type BucketAnalyticsConfigurationSpecManagementPoliciesItem string

// BucketAnalyticsConfigurationSpecProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
// create, observe, update, and delete this managed resource should be
// configured.
type BucketAnalyticsConfigurationSpecProviderConfigRef struct {
	// Kind Kind of the referenced object.
	Kind *string `json:"kind,omitempty"`

	// Name Name of the referenced object.
	Name *string `json:"name,omitempty"`
}

// BucketAnalyticsConfigurationSpecWriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
// Secret to which any connection details for this managed resource should
// be written. Connection details frequently include the endpoint, username,
// and password required to connect to the managed resource.
type BucketAnalyticsConfigurationSpecWriteConnectionSecretToRef struct {
	// Name Name of the secret.
	Name *string `json:"name,omitempty"`
}

// BucketAnalyticsConfigurationSpec BucketAnalyticsConfigurationSpec defines the desired state of BucketAnalyticsConfiguration
type BucketAnalyticsConfigurationSpec struct {
	ForProvider *BucketAnalyticsConfigurationSpecForProvider `json:"forProvider,omitempty"`

	// InitProvider THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider *BucketAnalyticsConfigurationSpecInitProvider `json:"initProvider,omitempty"`

	// ManagementPolicies THIS IS A BETA FIELD. It is on by default but can be opted out
	// through a Crossplane feature flag.
	// ManagementPolicies specify the array of actions Crossplane is allowed to
	// take on the managed and external resources.
	// See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
	// and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
	ManagementPolicies *[]BucketAnalyticsConfigurationSpecManagementPoliciesItem `json:"managementPolicies,omitempty"`

	// ProviderConfigRef ProviderConfigReference specifies how the provider that will be used to
	// create, observe, update, and delete this managed resource should be
	// configured.
	ProviderConfigRef *BucketAnalyticsConfigurationSpecProviderConfigRef `json:"providerConfigRef,omitempty"`

	// WriteConnectionSecretToRef WriteConnectionSecretToReference specifies the namespace and name of a
	// Secret to which any connection details for this managed resource should
	// be written. Connection details frequently include the endpoint, username,
	// and password required to connect to the managed resource.
	WriteConnectionSecretToRef *BucketAnalyticsConfigurationSpecWriteConnectionSecretToRef `json:"writeConnectionSecretToRef,omitempty"`
}

// BucketAnalyticsConfigurationStatusAtProviderFilter Object filtering that accepts a prefix, tags, or a logical AND of prefix and tags (documented below).
type BucketAnalyticsConfigurationStatusAtProviderFilter struct {
	// Prefix Object prefix for filtering.
	Prefix *string `json:"prefix,omitempty"`

	// Tags Key-value map of resource tags.
	Tags *map[string]string `json:"tags,omitempty"`
}

// BucketAnalyticsConfigurationStatusAtProviderStorageClassAnalysisDataExportDestinationS3BucketDestination Analytics data export currently only supports an S3 bucket destination (documented below).
type BucketAnalyticsConfigurationStatusAtProviderStorageClassAnalysisDataExportDestinationS3BucketDestination struct {
	// BucketAccountID Account ID that owns the destination bucket.
	BucketAccountID *string `json:"bucketAccountId,omitempty"`

	// BucketArn ARN of the destination bucket.
	BucketArn *string `json:"bucketArn,omitempty"`

	// Format Output format of exported analytics data. Allowed values: CSV. Default value: CSV.
	Format *string `json:"format,omitempty"`

	// Prefix Object prefix for filtering.
	Prefix *string `json:"prefix,omitempty"`
}

// BucketAnalyticsConfigurationStatusAtProviderStorageClassAnalysisDataExportDestination Specifies the destination for the exported analytics data (documented below).
type BucketAnalyticsConfigurationStatusAtProviderStorageClassAnalysisDataExportDestination struct {
	// S3BucketDestination Analytics data export currently only supports an S3 bucket destination (documented below).
	S3BucketDestination *BucketAnalyticsConfigurationStatusAtProviderStorageClassAnalysisDataExportDestinationS3BucketDestination `json:"s3BucketDestination,omitempty"`
}

// BucketAnalyticsConfigurationStatusAtProviderStorageClassAnalysisDataExport Data export configuration (documented below).
type BucketAnalyticsConfigurationStatusAtProviderStorageClassAnalysisDataExport struct {
	// Destination Specifies the destination for the exported analytics data (documented below).
	Destination *BucketAnalyticsConfigurationStatusAtProviderStorageClassAnalysisDataExportDestination `json:"destination,omitempty"`

	// OutputSchemaVersion Schema version of exported analytics data. Allowed values: V_1. Default value: V_1.
	OutputSchemaVersion *string `json:"outputSchemaVersion,omitempty"`
}

// BucketAnalyticsConfigurationStatusAtProviderStorageClassAnalysis Configuration for the analytics data export (documented below).
type BucketAnalyticsConfigurationStatusAtProviderStorageClassAnalysis struct {
	// DataExport Data export configuration (documented below).
	DataExport *BucketAnalyticsConfigurationStatusAtProviderStorageClassAnalysisDataExport `json:"dataExport,omitempty"`
}

// BucketAnalyticsConfigurationStatusAtProvider defines model for .
type BucketAnalyticsConfigurationStatusAtProvider struct {
	// Bucket Name of the bucket this analytics configuration is associated with.
	Bucket *string `json:"bucket,omitempty"`

	// Filter Object filtering that accepts a prefix, tags, or a logical AND of prefix and tags (documented below).
	Filter *BucketAnalyticsConfigurationStatusAtProviderFilter `json:"filter,omitempty"`
	ID     *string                                             `json:"id,omitempty"`

	// Name Unique identifier of the analytics configuration for the bucket.
	Name *string `json:"name,omitempty"`

	// Region Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty"`

	// StorageClassAnalysis Configuration for the analytics data export (documented below).
	StorageClassAnalysis *BucketAnalyticsConfigurationStatusAtProviderStorageClassAnalysis `json:"storageClassAnalysis,omitempty"`
}

// BucketAnalyticsConfigurationStatusConditionsItem A Condition that may apply to a resource.
type BucketAnalyticsConfigurationStatusConditionsItem struct {
	// LastTransitionTime LastTransitionTime is the last time this condition transitioned from one
	// status to another.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A Message containing details about this condition's last transition from
	// one status to another, if any.
	Message *string `json:"message,omitempty"`

	// ObservedGeneration ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	// For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
	// with respect to the current state of the instance.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A Reason for this condition's last transition from one status to another.
	Reason *string `json:"reason,omitempty"`

	// Status Status of this condition; is it currently True, False, or Unknown?
	Status *string `json:"status,omitempty"`

	// Type Type of this condition. At most one of each condition type may apply to
	// a resource at any point in time.
	Type *string `json:"type,omitempty"`
}

// BucketAnalyticsConfigurationStatus BucketAnalyticsConfigurationStatus defines the observed state of BucketAnalyticsConfiguration.
type BucketAnalyticsConfigurationStatus struct {
	AtProvider *BucketAnalyticsConfigurationStatusAtProvider `json:"atProvider,omitempty"`

	// Conditions Conditions of the resource.
	Conditions *[]BucketAnalyticsConfigurationStatusConditionsItem `json:"conditions,omitempty"`

	// ObservedGeneration ObservedGeneration is the latest metadata.generation
	// which resulted in either a ready state, or stalled due to error
	// it can not recover from without human intervention.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// BucketAnalyticsConfiguration BucketAnalyticsConfiguration is the Schema for the BucketAnalyticsConfigurations API. Provides a S3 bucket analytics configuration resource.
type BucketAnalyticsConfiguration struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *BucketAnalyticsConfigurationAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *BucketAnalyticsConfigurationKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`

	// Spec BucketAnalyticsConfigurationSpec defines the desired state of BucketAnalyticsConfiguration
	Spec *BucketAnalyticsConfigurationSpec `json:"spec,omitempty"`

	// Status BucketAnalyticsConfigurationStatus defines the observed state of BucketAnalyticsConfiguration.
	Status *BucketAnalyticsConfigurationStatus `json:"status,omitempty"`
}

// IoUpboundMAwsS3V1Beta1BucketAnalyticsConfigurationList BucketAnalyticsConfigurationList is a list of BucketAnalyticsConfiguration
type IoUpboundMAwsS3V1Beta1BucketAnalyticsConfigurationList = BucketAnalyticsConfigurationList

// BucketAnalyticsConfigurationList BucketAnalyticsConfigurationList is a list of BucketAnalyticsConfiguration
type BucketAnalyticsConfigurationList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of bucketanalyticsconfigurations. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]IoUpboundMAwsS3V1Beta1BucketAnalyticsConfiguration `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
