// Package v1alpha1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version v2.0.0-20260512191121-23c2b5646dfc+dirty DO NOT EDIT.
package v1alpha1

import (
	"encoding/json"
	"fmt"
	"time"

	metav1 "dev.crossplane.io/models/io/k8s/meta/v1"
	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)

// Defines values for WebAppAPIVersion.
const (
	WebAppAPIVersionplatformExampleComV1Alpha1 WebAppAPIVersion = "platform.example.com/v1alpha1"
)

// Valid indicates whether the value is a known member of the WebAppAPIVersion enum.
func (e WebAppAPIVersion) Valid() bool {
	switch e {
	case WebAppAPIVersionplatformExampleComV1Alpha1:
		return true
	default:
		return false
	}
}

// Defines values for WebAppKind.
const (
	WebAppKindWebApp WebAppKind = "WebApp"
)

// Valid indicates whether the value is a known member of the WebAppKind enum.
func (e WebAppKind) Valid() bool {
	switch e {
	case WebAppKindWebApp:
		return true
	default:
		return false
	}
}

// Defines values for WebAppSpecCrossplaneCompositionUpdatePolicy.
const (
	WebAppSpecCrossplaneCompositionUpdatePolicyAutomatic WebAppSpecCrossplaneCompositionUpdatePolicy = "Automatic"
	WebAppSpecCrossplaneCompositionUpdatePolicyManual    WebAppSpecCrossplaneCompositionUpdatePolicy = "Manual"
)

// Valid indicates whether the value is a known member of the WebAppSpecCrossplaneCompositionUpdatePolicy enum.
func (e WebAppSpecCrossplaneCompositionUpdatePolicy) Valid() bool {
	switch e {
	case WebAppSpecCrossplaneCompositionUpdatePolicyAutomatic:
		return true
	case WebAppSpecCrossplaneCompositionUpdatePolicyManual:
		return true
	default:
		return false
	}
}

// ComExamplePlatformV1Alpha1WebApp WebApp is the Schema for the WebApp API.
type ComExamplePlatformV1Alpha1WebApp = WebApp

// WebAppAPIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
type WebAppAPIVersion string

// WebAppKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
type WebAppKind string

// WebAppSpecCrossplaneCompositionRef defines model for .
type WebAppSpecCrossplaneCompositionRef struct {
	Name *string `json:"name,omitempty"`
}

// WebAppSpecCrossplaneCompositionRevisionRef defines model for .
type WebAppSpecCrossplaneCompositionRevisionRef struct {
	Name *string `json:"name,omitempty"`
}

// WebAppSpecCrossplaneCompositionRevisionSelector defines model for .
type WebAppSpecCrossplaneCompositionRevisionSelector struct {
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`
}

// WebAppSpecCrossplaneCompositionSelector defines model for .
type WebAppSpecCrossplaneCompositionSelector struct {
	MatchLabels *map[string]string `json:"matchLabels,omitempty"`
}

// WebAppSpecCrossplaneCompositionUpdatePolicy defines model for com.example.platform.v1alpha1.WebApp.spec.crossplane.compositionUpdatePolicy.
type WebAppSpecCrossplaneCompositionUpdatePolicy string

// WebAppSpecCrossplaneResourceRefsItem defines model for .
type WebAppSpecCrossplaneResourceRefsItem struct {
	APIVersion *string `json:"apiVersion,omitempty"`
	Kind       *string `json:"kind,omitempty"`
	Name       *string `json:"name,omitempty"`
}

// WebAppSpecCrossplane Configures how Crossplane will reconcile this composite resource
type WebAppSpecCrossplane struct {
	CompositionRef              *WebAppSpecCrossplaneCompositionRef              `json:"compositionRef,omitempty"`
	CompositionRevisionRef      *WebAppSpecCrossplaneCompositionRevisionRef      `json:"compositionRevisionRef,omitempty"`
	CompositionRevisionSelector *WebAppSpecCrossplaneCompositionRevisionSelector `json:"compositionRevisionSelector,omitempty"`
	CompositionSelector         *WebAppSpecCrossplaneCompositionSelector         `json:"compositionSelector,omitempty"`
	CompositionUpdatePolicy     *WebAppSpecCrossplaneCompositionUpdatePolicy     `json:"compositionUpdatePolicy,omitempty"`
	ResourceRefs                *[]WebAppSpecCrossplaneResourceRefsItem          `json:"resourceRefs,omitempty"`
}

// WebAppSpec defines model for .
type WebAppSpec struct {
	// Crossplane Configures how Crossplane will reconcile this composite resource
	Crossplane *WebAppSpecCrossplane `json:"crossplane,omitempty"`

	// Image OCI image for the webapp
	Image *string `json:"image,omitempty"`

	// Ports Ports to expose from the application container
	Ports *[]int `json:"ports,omitempty"`

	// Replicas Number of replicas to run
	Replicas *int `json:"replicas,omitempty"`
}

// WebAppStatusConditionsItem defines model for .
type WebAppStatusConditionsItem struct {
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`
	Message            *string    `json:"message,omitempty"`
	ObservedGeneration *int64     `json:"observedGeneration,omitempty"`
	Reason             *string    `json:"reason,omitempty"`
	Status             *string    `json:"status,omitempty"`
	Type               *string    `json:"type,omitempty"`
}

// WebAppStatus defines model for .
type WebAppStatus struct {
	// Conditions Conditions of the resource.
	Conditions *[]WebAppStatusConditionsItem `json:"conditions,omitempty"`
}

// WebApp WebApp is the Schema for the WebApp API.
type WebApp struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *WebAppAPIVersion `json:"apiVersion,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *WebAppKind `json:"kind,omitempty"`

	// Metadata Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	Metadata *metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec     *WebAppSpec        `json:"spec,omitempty"`
	Status   *WebAppStatus      `json:"status,omitempty"`
}

// ComExamplePlatformV1Alpha1WebAppList WebAppList is a list of WebApp
type ComExamplePlatformV1Alpha1WebAppList = WebAppList

// WebAppList WebAppList is a list of WebApp
type WebAppList struct {
	// APIVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`

	// Items List of webapps. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items *[]ComExamplePlatformV1Alpha1WebApp `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`

	// Metadata Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `json:"metadata,omitempty"`
}
