// Package v1 contains generated models.
//
// Code generated by github.com/crossplane/cli/v2 version v2.0.0-20260513213342-24660b90a028+dirty DO NOT EDIT.
package v1

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Use the following to avoid unused import errors.
var (
	_ *time.Time      = nil
	_ json.RawMessage = nil
	_                 = fmt.Errorf
	_                 = runtime.JSONMerge
)
